// CRUMB — database alimenti precaricato.
// Valori per 100 g di parte edibile (fonti: tabelle CREA / USDA, arrotondati).
// cn = carboidrati NETTI (totali − fibra). na = sodio in mg.
// unita: grammi per misura casalinga specifica dell'alimento (sovrascrive i default).
'use strict';

const ALIMENTI_BASE = [
  // — Carne bianca
  { id: 'pollo', nome: 'Petto di pollo', alias: ['pollo', 'petto pollo', 'petto di pollo'], kcal: 100, p: 23.3, cn: 0, f: 0, na: 60, porz: 150, tag: ['carne-bianca'], unita: { fetta: 100 } },
  { id: 'tacchino', nome: 'Fesa di tacchino', alias: ['tacchino', 'fesa tacchino', 'petto di tacchino'], kcal: 107, p: 24, cn: 0, f: 0, na: 50, porz: 150, tag: ['carne-bianca'], unita: { fetta: 100 } },
  { id: 'uova', nome: 'Uova', alias: ['uovo', 'uova', 'uova intere'], kcal: 128, p: 12.4, cn: 0, f: 0, na: 137, porz: 110, tag: [], unita: { pezzo: 55 } },
  { id: 'albume', nome: 'Albume', alias: ['albume', 'albumi', 'chiara d uovo'], kcal: 43, p: 10.7, cn: 0.7, f: 0, na: 179, porz: 100, tag: [], unita: { pezzo: 33 } },

  // — Pesce
  { id: 'merluzzo', nome: 'Merluzzo', alias: ['merluzzo', 'nasello', 'baccala dissalato'], kcal: 71, p: 17, cn: 0, f: 0, na: 77, porz: 200, tag: ['pesce'] },
  { id: 'platessa', nome: 'Platessa', alias: ['platessa', 'filetti di platessa'], kcal: 86, p: 18.8, cn: 0, f: 0, na: 100, porz: 200, tag: ['pesce'] },
  { id: 'branzino', nome: 'Branzino', alias: ['branzino', 'spigola'], kcal: 97, p: 18.4, cn: 0, f: 0, na: 70, porz: 250, tag: ['pesce'] },
  { id: 'orata', nome: 'Orata', alias: ['orata'], kcal: 121, p: 19.7, cn: 0, f: 0, na: 70, porz: 250, tag: ['pesce'] },
  { id: 'sgombro', nome: 'Sgombro', alias: ['sgombro', 'maccarello'], kcal: 170, p: 17, cn: 0, f: 0, na: 100, porz: 200, tag: ['pesce', 'pesce-azzurro'] },
  { id: 'alici', nome: 'Alici fresche', alias: ['alici', 'acciughe', 'acciuga', 'alice'], kcal: 96, p: 16.8, cn: 1.5, f: 0, na: 104, porz: 150, tag: ['pesce', 'pesce-azzurro'] },
  { id: 'sardine', nome: 'Sardine', alias: ['sardine', 'sarde', 'sardina'], kcal: 129, p: 20.8, cn: 0, f: 0, na: 100, porz: 150, tag: ['pesce', 'pesce-azzurro'] },
  { id: 'salmone-affumicato', nome: 'Salmone affumicato', alias: ['salmone affumicato', 'affumicato'], kcal: 147, p: 25.4, cn: 0, f: 0, na: 1880, porz: 100, tag: ['pesce', 'processato'], unita: { fetta: 15, confezione: 100 } },
  { id: 'salmone', nome: 'Salmone fresco', alias: ['salmone', 'salmone fresco', 'trancio di salmone'], kcal: 185, p: 20, cn: 0, f: 0, na: 59, porz: 150, tag: ['pesce'] },
  { id: 'tonno-naturale', nome: 'Tonno al naturale', alias: ['tonno', 'tonno al naturale', 'tonno in scatola'], kcal: 103, p: 23.3, cn: 0, f: 0, na: 320, porz: 80, tag: ['pesce', 'processato'], unita: { scatoletta: 56 } },
  { id: 'gamberi', nome: 'Gamberi', alias: ['gamberi', 'gamberetti', 'mazzancolle'], kcal: 71, p: 13.6, cn: 0.9, f: 0, na: 146, porz: 150, tag: ['pesce'] },

  // — Carne rossa
  { id: 'macinato-manzo', nome: 'Macinato di manzo', alias: ['macinato', 'macinato di manzo', 'carne macinata', 'hamburger', 'burger'], kcal: 176, p: 20, cn: 0, f: 0, na: 66, porz: 150, tag: ['carne-rossa'] },
  { id: 'manzo', nome: 'Manzo magro (bistecca)', alias: ['manzo', 'bistecca', 'fettina di manzo', 'tagliata', 'filetto di manzo'], kcal: 129, p: 21.5, cn: 0, f: 0, na: 60, porz: 180, tag: ['carne-rossa'], unita: { fetta: 120 } },

  // — Salumi (processati)
  { id: 'bresaola', nome: 'Bresaola', alias: ['bresaola'], kcal: 151, p: 32, cn: 0.4, f: 0, na: 1597, porz: 60, tag: ['carne-rossa', 'processato'], unita: { fetta: 8 } },
  { id: 'crudo', nome: 'Prosciutto crudo', alias: ['crudo', 'prosciutto crudo', 'prosciutto'], kcal: 224, p: 25.5, cn: 0, f: 0, na: 2578, porz: 50, tag: ['carne-rossa', 'processato'], unita: { fetta: 12 } },
  { id: 'cotto', nome: 'Prosciutto cotto', alias: ['cotto', 'prosciutto cotto'], kcal: 215, p: 19.8, cn: 0.9, f: 0, na: 648, porz: 50, tag: ['carne-rossa', 'processato'], unita: { fetta: 15 } },
  { id: 'speck', nome: 'Speck', alias: ['speck'], kcal: 303, p: 28.3, cn: 0.5, f: 0, na: 1810, porz: 50, tag: ['carne-rossa', 'processato'], unita: { fetta: 10 } },
  { id: 'mortadella', nome: 'Mortadella', alias: ['mortadella'], kcal: 317, p: 14.7, cn: 0.5, f: 0, na: 1000, porz: 50, tag: ['carne-rossa', 'processato'], unita: { fetta: 15 } },
  { id: 'salame', nome: 'Salame', alias: ['salame', 'salamino'], kcal: 392, p: 26.7, cn: 1.5, f: 0, na: 1500, porz: 40, tag: ['carne-rossa', 'processato'], unita: { fetta: 8 } },
  { id: 'salsiccia', nome: 'Salsiccia', alias: ['salsiccia', 'salsicce'], kcal: 304, p: 15.4, cn: 0.6, f: 0, na: 800, porz: 150, tag: ['carne-rossa', 'processato'], unita: { pezzo: 100 } },

  // — Latticini
  { id: 'parmigiano', nome: 'Parmigiano', alias: ['parmigiano', 'parmigiano reggiano', 'grana', 'grana padano'], kcal: 392, p: 33.5, cn: 0, f: 0, na: 600, porz: 30, tag: ['latticino'], unita: { cucchiaio: 5, cucchiaino: 2 } },
  { id: 'pecorino', nome: 'Pecorino', alias: ['pecorino', 'pecorino romano'], kcal: 387, p: 28.5, cn: 0.2, f: 0, na: 1800, porz: 30, tag: ['latticino'], unita: { cucchiaio: 5, cucchiaino: 2 } },
  { id: 'asiago', nome: 'Asiago', alias: ['asiago'], kcal: 360, p: 30, cn: 0.5, f: 0, na: 1000, porz: 40, tag: ['latticino'], unita: { fetta: 20 } },
  { id: 'scamorza', nome: 'Scamorza', alias: ['scamorza', 'scamorza affumicata', 'provola'], kcal: 334, p: 25, cn: 1, f: 0, na: 800, porz: 80, tag: ['latticino'], unita: { fetta: 20 } },
  { id: 'mozzarella', nome: 'Mozzarella', alias: ['mozzarella', 'fior di latte'], kcal: 253, p: 18.7, cn: 0.7, f: 0, na: 196, porz: 125, tag: ['latticino'], unita: { pezzo: 125, fetta: 25 } },
  { id: 'bufala', nome: 'Mozzarella di bufala', alias: ['bufala', 'mozzarella di bufala', 'mozzarella bufala'], kcal: 288, p: 16.7, cn: 0.4, f: 0, na: 180, porz: 125, tag: ['latticino'], unita: { pezzo: 125, fetta: 25 } },
  { id: 'ricotta', nome: 'Ricotta', alias: ['ricotta', 'ricotta vaccina'], kcal: 146, p: 8.8, cn: 3.5, f: 0, na: 78, porz: 100, tag: ['latticino'], unita: { cucchiaio: 25 } },
  { id: 'stracchino', nome: 'Stracchino', alias: ['stracchino', 'crescenza'], kcal: 300, p: 18.5, cn: 0, f: 0, na: 600, porz: 80, tag: ['latticino'] },
  { id: 'jocca', nome: 'Jocca (fiocchi di latte)', alias: ['jocca', 'fiocchi di latte', 'cottage cheese', 'cottage'], kcal: 100, p: 11.5, cn: 3.3, f: 0, na: 350, porz: 175, tag: ['latticino'], unita: { vasetto: 175, pezzo: 175 } },
  { id: 'yogurt-greco', nome: 'Yogurt greco 2%', alias: ['yogurt greco', 'greco', 'yogurt', 'fage', 'yogurt greco 2'], kcal: 73, p: 9.9, cn: 3, f: 0, na: 37, porz: 170, tag: ['latticino'], unita: { vasetto: 170, pezzo: 170, cucchiaio: 20 } },
  { id: 'latte', nome: 'Latte parzialmente scremato', alias: ['latte', 'latte ps', 'latte parzialmente scremato'], kcal: 46, p: 3.5, cn: 5, f: 0, na: 44, porz: 200, tag: ['latticino'], unita: { tazza: 250, bicchiere: 200 } },
  { id: 'burro', nome: 'Burro', alias: ['burro'], kcal: 758, p: 0.8, cn: 1.1, f: 0, na: 7, porz: 10, tag: ['latticino', 'grasso'], unita: { cucchiaio: 12, cucchiaino: 5, noce: 10 } },

  // — Grassi, frutta secca
  { id: 'olio-evo', nome: 'Olio EVO', alias: ['olio', 'olio evo', 'evo', 'olio d oliva', 'olio extravergine', 'olio di oliva'], kcal: 899, p: 0, cn: 0, f: 0, na: 0, porz: 10, tag: ['grasso'], unita: { cucchiaio: 10, cucchiaino: 4, filo: 5 } },
  { id: 'avocado', nome: 'Avocado', alias: ['avocado'], kcal: 160, p: 2, cn: 1.8, f: 6.7, na: 7, porz: 100, tag: ['grasso'], unita: { pezzo: 150 } },
  { id: 'mandorle', nome: 'Mandorle', alias: ['mandorle', 'mandorla'], kcal: 579, p: 21.2, cn: 9.1, f: 12.5, na: 1, porz: 30, tag: ['frutta-secca'], unita: { pezzo: 1.2 } },
  { id: 'noci', nome: 'Noci', alias: ['noci', 'noce', 'gherigli'], kcal: 654, p: 15.2, cn: 7, f: 6.7, na: 2, porz: 30, tag: ['frutta-secca'], unita: { pezzo: 5 } },
  { id: 'burro-arachidi', nome: 'Burro di arachidi', alias: ['burro di arachidi', 'peanut butter', 'crema di arachidi'], kcal: 588, p: 25, cn: 14, f: 6, na: 17, porz: 20, tag: ['frutta-secca', 'grasso'], unita: { cucchiaio: 16, cucchiaino: 6 } },
  { id: 'olive', nome: 'Olive', alias: ['olive', 'oliva', 'olive verdi', 'olive nere'], kcal: 145, p: 1, cn: 0.5, f: 3.3, na: 1556, porz: 30, tag: ['grasso', 'processato'], unita: { pezzo: 4 } },

  // — Verdure
  { id: 'zucchine', nome: 'Zucchine', alias: ['zucchine', 'zucchina', 'zucchini'], kcal: 17, p: 1.2, cn: 2.1, f: 1, na: 8, porz: 200, tag: ['verdura'], unita: { pezzo: 200 } },
  { id: 'melanzane', nome: 'Melanzane', alias: ['melanzane', 'melanzana'], kcal: 25, p: 1, cn: 2.9, f: 3, na: 2, porz: 200, tag: ['verdura'], unita: { pezzo: 300 } },
  { id: 'cicoria', nome: 'Cicoria', alias: ['cicoria', 'catalogna', 'puntarelle'], kcal: 23, p: 1.7, cn: 0.7, f: 4, na: 45, porz: 200, tag: ['verdura'] },
  { id: 'spinaci', nome: 'Spinaci', alias: ['spinaci', 'spinacio'], kcal: 23, p: 2.9, cn: 1.4, f: 2.2, na: 79, porz: 200, tag: ['verdura'] },
  { id: 'broccoli', nome: 'Broccoli', alias: ['broccoli', 'broccolo', 'cime di rapa'], kcal: 34, p: 2.8, cn: 4.4, f: 2.6, na: 33, porz: 200, tag: ['verdura'] },
  { id: 'cavolfiore', nome: 'Cavolfiore', alias: ['cavolfiore', 'cavolfiori'], kcal: 25, p: 1.9, cn: 3, f: 2, na: 30, porz: 200, tag: ['verdura'] },
  { id: 'misticanza', nome: 'Misticanza', alias: ['misticanza', 'insalata', 'lattuga', 'rucola', 'valeriana', 'songino'], kcal: 17, p: 1.4, cn: 1.2, f: 1.8, na: 28, porz: 80, tag: ['verdura'] },
  { id: 'finocchio', nome: 'Finocchio', alias: ['finocchio', 'finocchi'], kcal: 31, p: 1.2, cn: 4.2, f: 3.1, na: 52, porz: 200, tag: ['verdura'], unita: { pezzo: 250 } },
  { id: 'pomodori', nome: 'Pomodori', alias: ['pomodori', 'pomodoro', 'pomodorini', 'ciliegini'], kcal: 19, p: 1, cn: 2.7, f: 1.2, na: 5, porz: 150, tag: ['verdura'], unita: { pezzo: 120 } },
  { id: 'peperoni', nome: 'Peperoni', alias: ['peperoni', 'peperone'], kcal: 26, p: 1, cn: 3.9, f: 2.1, na: 4, porz: 200, tag: ['verdura'], unita: { pezzo: 200 } },
  { id: 'funghi', nome: 'Funghi champignon', alias: ['funghi', 'fungo', 'champignon'], kcal: 22, p: 3.1, cn: 2.3, f: 1, na: 5, porz: 150, tag: ['verdura'] },
  { id: 'cavolo-nero', nome: 'Cavolo nero', alias: ['cavolo nero', 'cavolo', 'verza', 'cavoli'], kcal: 35, p: 2.9, cn: 4.4, f: 4.1, na: 53, porz: 200, tag: ['verdura'] },
  { id: 'asparagi', nome: 'Asparagi', alias: ['asparagi', 'asparago'], kcal: 20, p: 2.2, cn: 1.8, f: 2.1, na: 2, porz: 200, tag: ['verdura'] },
  { id: 'cetrioli', nome: 'Cetrioli', alias: ['cetrioli', 'cetriolo'], kcal: 15, p: 0.7, cn: 3.1, f: 0.5, na: 2, porz: 150, tag: ['verdura'], unita: { pezzo: 200 } },

  // — Legumi
  { id: 'lenticchie', nome: 'Lenticchie (cotte)', alias: ['lenticchie', 'lenticchie cotte', 'lenticchia'], kcal: 116, p: 9, cn: 12.2, f: 7.9, na: 2, porz: 150, tag: ['legume'] },
  { id: 'lenticchie-secche', nome: 'Lenticchie secche', alias: ['lenticchie secche', 'lenticchie crude'], kcal: 352, p: 24.6, cn: 52.7, f: 10.7, na: 6, porz: 50, tag: ['legume'] },
  { id: 'ceci', nome: 'Ceci (cotti)', alias: ['ceci', 'ceci cotti', 'cece'], kcal: 164, p: 8.9, cn: 19.8, f: 7.6, na: 7, porz: 150, tag: ['legume'] },
  { id: 'fagioli', nome: 'Fagioli (cotti)', alias: ['fagioli', 'fagioli cotti', 'borlotti', 'cannellini', 'fagiolo'], kcal: 127, p: 8.7, cn: 16.4, f: 6.4, na: 2, porz: 150, tag: ['legume'] },

  // — Cereali e sostituti
  { id: 'pasta', nome: 'Pasta (secca)', alias: ['pasta', 'spaghetti', 'penne', 'fusilli', 'rigatoni'], kcal: 353, p: 12, cn: 71, f: 2.7, na: 3, porz: 80, tag: ['cereale'] },
  { id: 'riso', nome: 'Riso (crudo)', alias: ['riso', 'riso basmati', 'risotto'], kcal: 360, p: 7, cn: 78.7, f: 1.3, na: 5, porz: 80, tag: ['cereale'] },
  { id: 'pane-integrale', nome: 'Pane integrale', alias: ['pane integrale', 'pane integrale a fette'], kcal: 224, p: 7.5, cn: 42, f: 6.5, na: 530, porz: 50, tag: ['cereale'], unita: { fetta: 35 } },
  { id: 'shirataki', nome: 'Konjac / shirataki', alias: ['konjac', 'shirataki', 'pasta konjac', 'pasta di konjac', 'noodles konjac'], kcal: 9, p: 0, cn: 0, f: 3, na: 5, porz: 200, tag: [], unita: { confezione: 200 } },

  // — Frutta e altro
  { id: 'mela', nome: 'Mela', alias: ['mela', 'mele'], kcal: 52, p: 0.3, cn: 11.4, f: 2.4, na: 1, porz: 180, tag: [], unita: { pezzo: 180 } },
  { id: 'frutti-bosco', nome: 'Frutti di bosco', alias: ['frutti di bosco', 'mirtilli', 'lamponi', 'fragole', 'more'], kcal: 43, p: 0.9, cn: 6.5, f: 3.5, na: 1, porz: 100, tag: [], unita: { manciata: 50 } },
  { id: 'fondente', nome: 'Cioccolato fondente 85%', alias: ['cioccolato', 'fondente', 'cioccolato fondente', 'cioccolata'], kcal: 580, p: 12.5, cn: 19, f: 11, na: 20, porz: 20, tag: [], unita: { quadratino: 5, pezzo: 5 } },
  { id: 'proteine-whey', nome: 'Proteine whey', alias: ['whey', 'proteine', 'proteine in polvere', 'shake proteico', 'proteine whey'], kcal: 380, p: 78, cn: 6, f: 0, na: 200, porz: 30, tag: ['latticino'], unita: { misurino: 30, pezzo: 30 } },
];

// — Estensione del database (stesso formato, forma compatta).
// [id, nome, alias, kcal, proteine, carbo netti, fibra, sodio mg, porzione g, tag, unità]
const _A = (id, nome, alias, kcal, p, cn, f, na, porz, tag = [], unita) => ({ id, nome, alias, kcal, p, cn, f, na, porz, tag, ...(unita ? { unita } : {}) });
ALIMENTI_BASE.push(
  // Carne bianca
  _A('cosce-pollo', 'Cosce di pollo (senza pelle)', ['cosce di pollo', 'coscia di pollo', 'sovracosce', 'sovracoscia', 'sovraccoscio', 'sovraccosce', 'sovraccoscia', 'sovraccoscio di pollo', 'sovracoscia di pollo', 'sovracosce di pollo', 'sovraccosce di pollo', 'fusi di pollo', 'fuso di pollo', 'coscia', 'cosce'], 121, 19.7, 0, 0, 95, 200, ['carne-bianca'], { pezzo: 120 }),
  _A('ali-pollo', 'Ali di pollo', ['ali di pollo', 'alette', 'alette di pollo'], 203, 18.3, 0, 0, 73, 200, ['carne-bianca'], { pezzo: 35 }),
  _A('macinato-tacchino', 'Macinato di tacchino', ['macinato di tacchino', 'macinato di pollo', 'macinato bianco'], 148, 19.7, 0, 0, 70, 150, ['carne-bianca']),
  _A('coniglio', 'Coniglio', ['coniglio'], 114, 21.2, 0, 0, 49, 200, ['carne-bianca']),
  _A('tacchino-affettato', 'Fesa di tacchino affettata', ['fesa di tacchino affettata', 'affettato di tacchino', 'petto di tacchino affettato'], 100, 20, 1, 0, 900, 50, ['carne-bianca', 'processato'], { fetta: 10 }),
  _A('cotoletta-pollo', 'Cotoletta di pollo impanata', ['cotoletta', 'cotoletta di pollo', 'cotoletta impanata', 'pollo impanato', 'nuggets'], 230, 16, 12, 1, 400, 150, ['carne-bianca'], { pezzo: 120 }),
  _A('wurstel', 'Würstel', ['wurstel', 'würstel', 'hot dog', 'wurstel di pollo'], 250, 13, 2, 0, 900, 100, ['processato'], { pezzo: 50 }),

  // Carne rossa
  _A('lonza', 'Lonza di maiale', ['lonza', 'arista', 'braciola di maiale', 'maiale', 'lombata di maiale', 'filetto di maiale'], 146, 21, 0, 0, 55, 180, ['carne-rossa'], { fetta: 120 }),
  _A('vitello', 'Vitello (fesa)', ['vitello', 'fettina di vitello', 'scaloppine', 'fesa di vitello'], 109, 21, 0, 0, 80, 150, ['carne-rossa'], { fetta: 100 }),
  _A('agnello', 'Agnello', ['agnello', 'costolette di agnello', 'abbacchio'], 159, 20, 0, 0, 70, 200, ['carne-rossa']),
  _A('cavallo', 'Carne di cavallo', ['cavallo', 'carne di cavallo', 'pesto di cavallo'], 133, 21.4, 0, 0, 53, 150, ['carne-rossa']),
  _A('fegato', 'Fegato di vitello', ['fegato', 'fegato di vitello'], 135, 20, 4, 0, 70, 150, ['carne-rossa']),
  _A('roast-beef', 'Roast beef', ['roast beef', 'roastbeef', 'rosbif'], 150, 26, 0.5, 0, 500, 80, ['carne-rossa', 'processato'], { fetta: 15 }),
  _A('pancetta', 'Pancetta', ['pancetta', 'pancetta affumicata', 'cubetti di pancetta', 'bacon'], 400, 14, 0, 0, 1500, 30, ['carne-rossa', 'processato'], { fetta: 10 }),
  _A('guanciale', 'Guanciale', ['guanciale'], 650, 9, 0, 0, 1500, 30, ['carne-rossa', 'processato'], { fetta: 10 }),
  _A('coppa', 'Coppa', ['coppa', 'capocollo'], 360, 24, 0.5, 0, 1800, 50, ['carne-rossa', 'processato'], { fetta: 10 }),
  _A('kebab', 'Kebab (piadina/pita)', ['kebab', 'doner', 'kebab piadina', 'gyros'], 215, 12, 18, 1.5, 600, 350, ['carne-rossa', 'processato', 'cereale'], { pezzo: 350 }),

  // Pesce
  _A('tonno-fresco', 'Tonno fresco', ['tonno fresco', 'trancio di tonno', 'tataki di tonno'], 130, 24, 0, 0, 40, 200, ['pesce', 'pesce-azzurro']),
  _A('tonno-olio', "Tonno sott'olio (sgocciolato)", ['tonno sott olio', 'tonno all olio', 'tonno in olio'], 192, 25, 0, 0, 300, 80, ['pesce', 'processato'], { scatoletta: 52 }),
  _A('pesce-spada', 'Pesce spada', ['pesce spada', 'spada'], 121, 19.8, 0, 0, 90, 200, ['pesce']),
  _A('sogliola', 'Sogliola', ['sogliola', 'sogliole'], 83, 17, 0, 0, 80, 200, ['pesce']),
  _A('trota', 'Trota', ['trota', 'salmerino'], 119, 20.5, 0, 0, 52, 200, ['pesce']),
  _A('rombo', 'Rombo', ['rombo', 'rombo chiodato'], 95, 16.3, 0, 0, 100, 200, ['pesce']),
  _A('polpo', 'Polpo', ['polpo', 'polipo', 'moscardini'], 57, 10.6, 1.4, 0, 220, 250, ['pesce']),
  _A('calamari', 'Calamari', ['calamari', 'calamaro', 'totani', 'totano'], 68, 12.6, 0.6, 0, 160, 200, ['pesce']),
  _A('seppie', 'Seppie', ['seppie', 'seppia', 'seppioline'], 72, 14, 0.7, 0, 370, 200, ['pesce']),
  _A('cozze', 'Cozze (sgusciate)', ['cozze', 'cozza', 'muscoli'], 84, 11.7, 3.4, 0, 290, 150, ['pesce']),
  _A('vongole', 'Vongole (sgusciate)', ['vongole', 'vongola', 'lupini di mare'], 72, 10.2, 2.2, 0, 400, 100, ['pesce']),
  _A('baccala', 'Baccalà ammollato', ['baccala', 'stoccafisso', 'baccala ammollato'], 95, 21.6, 0, 0, 300, 200, ['pesce']),
  _A('sardine-olio', "Sardine sott'olio", ['sardine sott olio', 'sardine in scatola'], 208, 24.6, 0, 0, 505, 90, ['pesce', 'pesce-azzurro', 'processato'], { scatoletta: 90 }),
  _A('sgombro-scatola', 'Sgombro in scatola', ['sgombro in scatola', 'sgombro sott olio', 'sgombro al naturale'], 200, 19, 0, 0, 380, 90, ['pesce', 'pesce-azzurro', 'processato'], { scatoletta: 90 }),
  _A('acciughe-olio', "Acciughe sott'olio", ['acciughe sott olio', 'filetti di acciuga', 'alici sott olio'], 206, 29, 0, 0, 3600, 20, ['pesce', 'pesce-azzurro', 'processato'], { pezzo: 4 }),
  _A('surimi', 'Surimi', ['surimi', 'bastoncini di surimi', 'polpa di granchio'], 99, 15, 6.9, 0, 700, 100, ['pesce', 'processato'], { pezzo: 17 }),
  _A('bastoncini-pesce', 'Bastoncini di pesce', ['bastoncini di pesce', 'bastoncini', 'fish sticks'], 205, 12, 17, 1, 400, 100, ['pesce', 'processato'], { pezzo: 25 }),
  _A('sushi', 'Sushi misto (nigiri/maki)', ['sushi', 'nigiri', 'maki', 'uramaki', 'sashimi e riso'], 150, 6, 28, 0.5, 400, 250, ['pesce', 'cereale'], { pezzo: 30 }),
  _A('salmone-scatola', 'Salmone in scatola', ['salmone in scatola', 'salmone al naturale'], 139, 23, 0, 0, 380, 100, ['pesce', 'processato'], { scatoletta: 100 }),

  // Latticini
  _A('latte-intero', 'Latte intero', ['latte intero'], 64, 3.3, 4.9, 0, 50, 200, ['latticino'], { tazza: 250, bicchiere: 200 }),
  _A('latte-scremato', 'Latte scremato', ['latte scremato', 'latte magro'], 34, 3.4, 5, 0, 52, 200, ['latticino'], { tazza: 250, bicchiere: 200 }),
  _A('yogurt-intero', 'Yogurt bianco intero', ['yogurt bianco', 'yogurt intero', 'yogurt naturale'], 66, 3.8, 4.3, 0, 48, 125, ['latticino'], { vasetto: 125, pezzo: 125 }),
  _A('greco-0', 'Yogurt greco 0%', ['yogurt greco 0', 'greco 0', 'yogurt greco magro', 'greco magro'], 54, 10, 3.5, 0, 36, 170, ['latticino'], { vasetto: 170, pezzo: 170, cucchiaio: 20 }),
  _A('greco-intero', 'Yogurt greco intero', ['yogurt greco intero', 'greco intero', 'greco 5%', 'greco 10%'], 97, 9, 3.8, 0, 35, 170, ['latticino'], { vasetto: 170, pezzo: 170, cucchiaio: 20 }),
  _A('skyr', 'Skyr', ['skyr'], 63, 11, 4, 0, 50, 150, ['latticino'], { vasetto: 150, pezzo: 150 }),
  _A('yogurt-proteico', 'Yogurt proteico', ['yogurt proteico', 'hipro', 'yogurt high protein'], 60, 10, 4, 0, 50, 160, ['latticino'], { vasetto: 160, pezzo: 160 }),
  _A('budino-proteico', 'Budino proteico', ['budino proteico', 'pudding proteico'], 80, 10, 7, 0, 100, 200, ['latticino'], { vasetto: 200, pezzo: 200 }),
  _A('kefir', 'Kefir', ['kefir'], 52, 3.4, 4.5, 0, 40, 200, ['latticino'], { bicchiere: 200 }),
  _A('emmental', 'Emmental', ['emmental', 'emmenthal', 'groviera', 'gruviera'], 380, 28.5, 0, 0, 200, 30, ['latticino'], { fetta: 20 }),
  _A('fontina', 'Fontina', ['fontina'], 343, 24.5, 0.8, 0, 600, 40, ['latticino'], { fetta: 20 }),
  _A('gorgonzola', 'Gorgonzola', ['gorgonzola', 'erborinato'], 324, 19.1, 0, 0, 1100, 40, ['latticino']),
  _A('taleggio', 'Taleggio', ['taleggio'], 315, 19, 0.9, 0, 800, 40, ['latticino']),
  _A('provolone', 'Provolone', ['provolone'], 374, 28, 1, 0, 900, 40, ['latticino'], { fetta: 20 }),
  _A('caciocavallo', 'Caciocavallo', ['caciocavallo'], 390, 30, 1, 0, 900, 40, ['latticino'], { fetta: 20 }),
  _A('feta', 'Feta', ['feta'], 264, 14.2, 4.1, 0, 1116, 50, ['latticino']),
  _A('burrata', 'Burrata', ['burrata', 'stracciatella'], 290, 15, 1, 0, 200, 125, ['latticino'], { pezzo: 125 }),
  _A('mozzarella-light', 'Mozzarella light', ['mozzarella light', 'mozzarella magra'], 163, 19, 1, 0, 200, 125, ['latticino'], { pezzo: 125 }),
  _A('robiola', 'Robiola', ['robiola'], 283, 16, 3, 0, 500, 50, ['latticino']),
  _A('spalmabile', 'Formaggio spalmabile', ['formaggio spalmabile', 'philadelphia', 'spalmabile', 'formaggio fresco spalmabile'], 235, 5.5, 4, 0, 320, 30, ['latticino'], { cucchiaio: 15 }),
  _A('mascarpone', 'Mascarpone', ['mascarpone'], 453, 7.6, 3.5, 0, 45, 30, ['latticino', 'grasso'], { cucchiaio: 20 }),
  _A('panna', 'Panna da cucina', ['panna', 'panna da cucina', 'panna fresca'], 200, 2.5, 3.5, 0, 40, 30, ['latticino', 'grasso'], { cucchiaio: 15 }),
  _A('gelato', 'Gelato (fior di latte)', ['gelato', 'coppetta gelato', 'cono gelato'], 200, 3.8, 24, 0.7, 70, 100, ['latticino'], { pallina: 50 }),

  // Grassi, frutta secca e semi
  _A('olio-semi', 'Olio di semi', ['olio di semi', 'olio di girasole', 'olio di arachidi', 'olio di mais'], 899, 0, 0, 0, 0, 10, ['grasso'], { cucchiaio: 10, cucchiaino: 4 }),
  _A('olio-cocco', 'Olio di cocco', ['olio di cocco'], 892, 0, 0, 0, 0, 10, ['grasso'], { cucchiaio: 10, cucchiaino: 4 }),
  _A('nocciole', 'Nocciole', ['nocciole', 'nocciola'], 628, 15, 7, 9.7, 0, 30, ['frutta-secca'], { pezzo: 1.3 }),
  _A('pistacchi', 'Pistacchi', ['pistacchi', 'pistacchio'], 562, 20.2, 17.1, 10.6, 1, 30, ['frutta-secca'], { pezzo: 0.7 }),
  _A('anacardi', 'Anacardi', ['anacardi', 'anacardo'], 553, 18.2, 27, 3.3, 12, 30, ['frutta-secca'], { pezzo: 1.5 }),
  _A('arachidi', 'Arachidi tostate', ['arachidi', 'noccioline', 'arachidi tostate'], 585, 24, 13, 8.5, 6, 30, ['frutta-secca'], { pezzo: 0.8 }),
  _A('noci-brasile', 'Noci del Brasile', ['noci del brasile', 'noce del brasile'], 659, 14.3, 4.2, 7.5, 3, 20, ['frutta-secca'], { pezzo: 5 }),
  _A('chia', 'Semi di chia', ['chia', 'semi di chia'], 486, 16.5, 7.7, 34.4, 16, 15, ['frutta-secca'], { cucchiaio: 12, cucchiaino: 4 }),
  _A('lino', 'Semi di lino', ['semi di lino', 'lino'], 534, 18.3, 1.6, 27.3, 30, 10, ['frutta-secca'], { cucchiaio: 10, cucchiaino: 4 }),
  _A('semi-zucca', 'Semi di zucca', ['semi di zucca'], 559, 30.2, 4.7, 6, 7, 30, ['frutta-secca'], { cucchiaio: 10 }),
  _A('semi-girasole', 'Semi di girasole', ['semi di girasole'], 584, 20.8, 11.4, 8.6, 9, 30, ['frutta-secca'], { cucchiaio: 10 }),
  _A('tahina', 'Tahina', ['tahina', 'tahini', 'crema di sesamo'], 595, 17, 11.9, 9.3, 115, 15, ['frutta-secca', 'grasso'], { cucchiaio: 15, cucchiaino: 5 }),
  _A('burro-mandorle', 'Burro di mandorle', ['burro di mandorle', 'crema di mandorle'], 614, 21, 8.5, 10.3, 7, 15, ['frutta-secca', 'grasso'], { cucchiaio: 16, cucchiaino: 6 }),
  _A('farina-mandorle', 'Farina di mandorle', ['farina di mandorle'], 600, 24, 9, 10, 1, 30, ['frutta-secca'], { cucchiaio: 8 }),
  _A('cocco', 'Cocco fresco', ['cocco', 'cocco fresco', 'cocco rape'], 354, 3.3, 6.2, 9, 20, 50, ['grasso']),
  _A('fondente-70', 'Cioccolato fondente 70%', ['cioccolato fondente 70%', 'fondente 70%', 'fondente al 70%'], 598, 7.8, 34, 10.9, 20, 20, [], { quadratino: 5, pezzo: 5 }),
  _A('maionese', 'Maionese', ['maionese'], 680, 1, 1, 0, 600, 15, ['grasso', 'processato'], { cucchiaio: 15, cucchiaino: 5 }),
  _A('pesto', 'Pesto alla genovese', ['pesto', 'pesto alla genovese', 'pesto genovese'], 480, 5, 4, 2, 1000, 30, ['grasso', 'processato'], { cucchiaio: 15 }),

  // Verdure
  _A('radicchio', 'Radicchio', ['radicchio', 'radicchio rosso', 'trevisano'], 23, 1.4, 3.6, 0.9, 22, 100, ['verdura']),
  _A('scarola', 'Scarola / indivia', ['scarola', 'indivia', 'riccia', 'belga'], 17, 1.3, 0.3, 3.1, 22, 200, ['verdura']),
  _A('bietola', 'Bietola', ['bietola', 'bietole', 'erbette', 'coste'], 19, 1.8, 2.1, 1.6, 213, 200, ['verdura']),
  _A('cavolini', 'Cavolini di Bruxelles', ['cavolini', 'cavolini di bruxelles', 'cavoletti'], 43, 3.4, 5.2, 3.8, 25, 200, ['verdura']),
  _A('cappuccio', 'Cavolo cappuccio', ['cavolo cappuccio', 'cappuccio', 'cavolo viola', 'cavolo rosso'], 25, 1.3, 3.3, 2.5, 18, 200, ['verdura']),
  _A('carciofi', 'Carciofi', ['carciofi', 'carciofo'], 47, 3.3, 5.1, 5.4, 94, 200, ['verdura'], { pezzo: 50 }),
  _A('carote', 'Carote', ['carote', 'carota'], 41, 0.9, 6.8, 2.8, 69, 100, ['verdura'], { pezzo: 80 }),
  _A('sedano', 'Sedano', ['sedano', 'costa di sedano'], 16, 0.7, 1.4, 1.6, 80, 100, ['verdura'], { pezzo: 40 }),
  _A('cipolla', 'Cipolla', ['cipolla', 'cipolle', 'cipollotto', 'scalogno'], 40, 1.1, 7.6, 1.7, 4, 50, ['verdura'], { pezzo: 100 }),
  _A('porri', 'Porri', ['porri', 'porro'], 61, 1.5, 12.4, 1.8, 20, 100, ['verdura'], { pezzo: 150 }),
  _A('fagiolini', 'Fagiolini', ['fagiolini', 'cornetti'], 31, 1.8, 4.3, 2.7, 6, 200, ['verdura']),
  _A('zucca', 'Zucca', ['zucca', 'zucca delica'], 26, 1, 6, 0.5, 1, 200, ['verdura']),
  _A('ravanelli', 'Ravanelli', ['ravanelli', 'ravanello'], 16, 0.7, 1.8, 1.6, 39, 100, ['verdura']),
  _A('germogli', 'Germogli di soia', ['germogli', 'germogli di soia'], 30, 3, 4.1, 1.8, 6, 100, ['verdura']),
  _A('barbabietola', 'Barbabietola cotta', ['barbabietola', 'barbabietole', 'rapa rossa'], 44, 1.7, 8, 2, 77, 100, ['verdura'], { pezzo: 100 }),
  _A('crauti', 'Crauti', ['crauti'], 19, 0.9, 1.4, 2.9, 661, 100, ['verdura', 'processato']),
  _A('passata', 'Passata di pomodoro', ['passata', 'passata di pomodoro', 'sugo', 'sugo di pomodoro', 'pelati', 'polpa di pomodoro'], 24, 1.3, 3.7, 1.2, 10, 100, ['verdura'], { cucchiaio: 20 }),
  _A('minestrone', 'Minestrone di verdure', ['minestrone', 'zuppa di verdure', 'passato di verdure', 'vellutata'], 45, 2, 6, 2.5, 200, 250, ['verdura']),
  _A('verdure-grigliate', 'Verdure grigliate', ['verdure grigliate', 'grigliata di verdure', 'verdure miste'], 30, 1.3, 3.5, 2.3, 10, 200, ['verdura']),
  _A('parmigiana', 'Parmigiana di melanzane', ['parmigiana', 'parmigiana di melanzane'], 150, 6.5, 6, 2.5, 350, 250, ['verdura', 'latticino']),

  // Patate e tuberi
  _A('patate', 'Patate', ['patate', 'patata'], 77, 2, 15.4, 2.1, 6, 200, [], { pezzo: 150 }),
  _A('patate-dolci', 'Patate dolci', ['patate dolci', 'patata dolce', 'patata americana', 'batata'], 86, 1.6, 17.1, 3, 55, 200, [], { pezzo: 200 }),
  _A('patatine-fritte', 'Patatine fritte', ['patatine fritte', 'patate fritte', 'french fries'], 312, 3.4, 38, 3.8, 210, 150, ['processato']),
  _A('patatine-busta', 'Patatine in busta', ['patatine', 'patatine in busta', 'chips'], 527, 6.6, 49, 4, 500, 30, ['processato'], { confezione: 30 }),

  // Legumi
  _A('piselli', 'Piselli', ['piselli', 'pisellini'], 81, 5.4, 9.4, 5.1, 5, 100, ['legume']),
  _A('edamame', 'Edamame', ['edamame', 'fagioli di soia'], 121, 11.9, 3.7, 5.2, 6, 100, ['legume']),
  _A('tofu', 'Tofu', ['tofu'], 120, 12.5, 1.2, 1.5, 10, 150, ['legume']),
  _A('tempeh', 'Tempeh', ['tempeh'], 192, 20, 6, 3, 9, 100, ['legume']),
  _A('seitan', 'Seitan', ['seitan'], 120, 25, 4, 0.5, 300, 100, ['cereale', 'processato']),
  _A('fagioli-secchi', 'Fagioli secchi', ['fagioli secchi', 'borlotti secchi', 'cannellini secchi'], 333, 23.6, 44.8, 15.2, 12, 50, ['legume']),
  _A('ceci-secchi', 'Ceci secchi', ['ceci secchi', 'ceci crudi'], 364, 19.3, 43.3, 17.4, 24, 50, ['legume']),
  _A('lenticchie-rosse', 'Lenticchie rosse decorticate', ['lenticchie rosse', 'lenticchie decorticate'], 358, 24, 52.4, 10.7, 6, 50, ['legume']),
  _A('lupini', 'Lupini', ['lupini'], 119, 15.6, 7.1, 2.8, 400, 100, ['legume']),
  _A('hummus', 'Hummus', ['hummus', 'humus', 'crema di ceci'], 166, 7.9, 8.3, 6, 380, 50, ['legume', 'processato'], { cucchiaio: 20 }),
  _A('pasta-legumi', 'Pasta di legumi', ['pasta di legumi', 'pasta di lenticchie', 'pasta di ceci', 'pasta di piselli'], 340, 25, 46, 9, 10, 80, ['legume']),
  _A('latte-soia', 'Bevanda di soia', ['latte di soia', 'bevanda di soia', 'bevanda soia'], 33, 3.3, 0.3, 0.6, 35, 200, ['legume'], { tazza: 250, bicchiere: 200 }),
  _A('latte-mandorla', 'Bevanda di mandorla (senza zucchero)', ['latte di mandorla', 'bevanda di mandorla', 'bevanda alla mandorla'], 13, 0.4, 0.3, 0.2, 70, 200, [], { tazza: 250, bicchiere: 200 }),

  // Cereali, pane e derivati
  _A('pasta-integrale', 'Pasta integrale', ['pasta integrale', 'spaghetti integrali', 'penne integrali'], 348, 13.4, 60, 7, 8, 80, ['cereale']),
  _A('riso-integrale', 'Riso integrale', ['riso integrale', 'riso venere', 'riso rosso'], 362, 7.5, 72.7, 3.5, 4, 80, ['cereale']),
  _A('farro', 'Farro', ['farro'], 335, 15.1, 60, 6.8, 18, 80, ['cereale']),
  _A('orzo', 'Orzo perlato', ['orzo', 'orzo perlato'], 352, 9.9, 62.1, 15.6, 9, 80, ['cereale']),
  _A('quinoa', 'Quinoa', ['quinoa'], 368, 14.1, 57.2, 7, 5, 80, ['cereale']),
  _A('couscous', 'Cous cous', ['cous cous', 'couscous', 'cuscus'], 376, 12.8, 72.4, 5, 10, 80, ['cereale']),
  _A('grano-saraceno', 'Grano saraceno', ['grano saraceno', 'saraceno'], 343, 13.3, 61.5, 10, 1, 80, ['cereale']),
  _A('avena', "Fiocchi d'avena", ['fiocchi d avena', 'avena', 'fiocchi di avena'], 379, 13.2, 57.6, 10.1, 6, 40, ['cereale'], { cucchiaio: 8 }),
  _A('polenta', 'Polenta (farina di mais)', ['polenta', 'farina di mais'], 362, 8.7, 72, 3.8, 1, 80, ['cereale']),
  _A('gnocchi', 'Gnocchi di patate', ['gnocchi', 'gnocchi di patate'], 150, 3.5, 32, 1.5, 400, 200, ['cereale', 'processato']),
  _A('pasta-fresca', "Pasta fresca all'uovo", ['pasta fresca', 'pasta all uovo', 'tagliatelle', 'fettuccine', 'tortellini', 'ravioli'], 280, 11, 50, 2, 30, 125, ['cereale']),
  _A('pane', 'Pane bianco', ['pane', 'pane bianco', 'pane comune', 'fetta di pane', 'rosetta', 'baguette', 'pane casereccio'], 270, 8.5, 53, 3, 500, 50, ['cereale'], { fetta: 30, pezzo: 60 }),
  _A('pane-segale', 'Pane di segale', ['pane di segale', 'pane nero', 'segale'], 259, 8.5, 42.1, 5.8, 603, 50, ['cereale'], { fetta: 30 }),
  _A('pane-proteico', 'Pane proteico / low carb', ['pane proteico', 'pane low carb', 'pane keto'], 265, 23, 7, 12, 500, 70, ['cereale'], { fetta: 35 }),
  _A('fette-biscottate', 'Fette biscottate', ['fette biscottate', 'fetta biscottata'], 405, 11.3, 71, 3.5, 450, 20, ['cereale'], { pezzo: 9, fetta: 9 }),
  _A('crackers', 'Crackers', ['crackers', 'cracker', 'craker'], 428, 9.4, 66, 3, 700, 25, ['cereale', 'processato'], { pezzo: 6, confezione: 25 }),
  _A('gallette', 'Gallette di riso', ['gallette', 'gallette di riso', 'gallette di mais'], 387, 8, 78.5, 3, 20, 16, ['cereale'], { pezzo: 8 }),
  _A('grissini', 'Grissini', ['grissini', 'grissino'], 410, 12, 65, 3.5, 700, 20, ['cereale', 'processato'], { pezzo: 5 }),
  _A('piadina', 'Piadina', ['piadina', 'piada'], 316, 8, 49, 2.5, 800, 100, ['cereale'], { pezzo: 100 }),
  _A('wrap', 'Tortilla / wrap', ['wrap', 'tortilla', 'tortillas'], 306, 8.2, 47, 3.5, 600, 60, ['cereale'], { pezzo: 60 }),
  _A('pizza', 'Pizza margherita', ['pizza', 'pizza margherita', 'margherita'], 250, 11, 32, 2, 550, 350, ['cereale', 'latticino'], { pezzo: 350, fetta: 45 }),
  _A('lasagne', 'Lasagne alla bolognese', ['lasagne', 'lasagna', 'pasta al forno'], 160, 8.5, 15, 1, 400, 300, ['cereale', 'carne-rossa', 'latticino']),
  _A('cornflakes', 'Corn flakes', ['cornflakes', 'corn flakes', 'cereali', 'cereali colazione'], 360, 7.5, 80, 3, 660, 30, ['cereale', 'processato']),
  _A('muesli', 'Muesli', ['muesli', 'granola'], 360, 9.8, 58, 8, 15, 40, ['cereale']),
  _A('biscotti', 'Biscotti secchi', ['biscotti', 'biscotto', 'frollini'], 450, 7, 70, 2.5, 300, 30, ['cereale', 'processato'], { pezzo: 8 }),
  _A('cornetto', 'Cornetto / brioche', ['cornetto', 'brioche', 'croissant'], 406, 8, 44, 2, 400, 60, ['cereale', 'processato'], { pezzo: 60 }),
  _A('pangrattato', 'Pangrattato', ['pangrattato', 'pan grattato', 'impanatura'], 395, 13, 72, 3.5, 700, 20, ['cereale'], { cucchiaio: 8 }),
  _A('focaccia', 'Focaccia', ['focaccia', 'focaccia genovese', 'focaccia all olio'], 300, 7, 43, 2, 800, 100, ['cereale'], { pezzo: 100, fetta: 80 }),
  _A('farina', 'Farina 00', ['farina', 'farina 00', 'farina bianca'], 340, 11, 74, 2.2, 1, 50, ['cereale'], { cucchiaio: 10 }),
  _A('barretta-proteica', 'Barretta proteica', ['barretta proteica', 'protein bar', 'barretta'], 360, 33, 12, 8, 300, 60, ['processato'], { pezzo: 60 }),

  // Frutta
  _A('banana', 'Banana', ['banana', 'banane'], 89, 1.1, 20.2, 2.6, 1, 120, [], { pezzo: 120 }),
  _A('arancia', 'Arancia', ['arancia', 'arance'], 47, 0.9, 9.4, 2.4, 0, 150, [], { pezzo: 150 }),
  _A('mandarino', 'Mandarino / clementina', ['mandarino', 'mandarini', 'clementina', 'clementine'], 53, 0.8, 11.5, 1.8, 2, 80, [], { pezzo: 80 }),
  _A('pera', 'Pera', ['pera', 'pere'], 57, 0.4, 12.1, 3.1, 1, 170, [], { pezzo: 170 }),
  _A('kiwi', 'Kiwi', ['kiwi'], 61, 1.1, 11.7, 3, 3, 80, [], { pezzo: 80 }),
  _A('pesca', 'Pesca', ['pesca', 'pesche', 'nettarina', 'nettarine'], 39, 0.9, 8, 1.5, 0, 150, [], { pezzo: 150 }),
  _A('albicocche', 'Albicocche', ['albicocche', 'albicocca'], 48, 1.4, 9.1, 2, 1, 40, [], { pezzo: 40 }),
  _A('uva', 'Uva', ['uva', 'acino', 'grappolo'], 69, 0.7, 17.2, 0.9, 2, 150, []),
  _A('ananas', 'Ananas', ['ananas'], 50, 0.5, 11.7, 1.4, 1, 150, [], { fetta: 80 }),
  _A('anguria', 'Anguria', ['anguria', 'cocomero'], 30, 0.6, 7.2, 0.4, 1, 300, [], { fetta: 300 }),
  _A('melone', 'Melone', ['melone'], 34, 0.8, 7.3, 0.9, 16, 200, [], { fetta: 150 }),
  _A('ciliegie', 'Ciliegie', ['ciliegie', 'ciliegia', 'amarene'], 63, 1.1, 14, 2.1, 0, 150, [], { pezzo: 7 }),
  _A('fichi', 'Fichi', ['fichi', 'fico'], 74, 0.8, 16.3, 2.9, 1, 100, [], { pezzo: 50 }),
  _A('cachi', 'Cachi', ['cachi', 'caco', 'kaki'], 70, 0.6, 15, 3.6, 1, 180, [], { pezzo: 180 }),
  _A('datteri', 'Datteri', ['datteri', 'dattero'], 282, 2.5, 67, 8, 2, 30, [], { pezzo: 8 }),
  _A('uvetta', 'Uvetta', ['uvetta', 'uva passa', 'uva sultanina'], 299, 3.1, 75.3, 3.7, 11, 20, [], { cucchiaio: 12 }),
  _A('prugne-secche', 'Prugne secche', ['prugne secche', 'prugne', 'prugna'], 240, 2.2, 56.5, 7.1, 2, 30, [], { pezzo: 8 }),

  // Condimenti, dolci, bevande
  _A('zucchero', 'Zucchero', ['zucchero', 'zucchero di canna'], 400, 0, 100, 0, 1, 5, [], { cucchiaino: 5, cucchiaio: 12, bustina: 5 }),
  _A('miele', 'Miele', ['miele'], 304, 0.3, 82.2, 0.2, 4, 10, [], { cucchiaino: 7, cucchiaio: 21 }),
  _A('marmellata', 'Marmellata / confettura', ['marmellata', 'confettura'], 250, 0.4, 61, 1, 20, 20, [], { cucchiaino: 10, cucchiaio: 20 }),
  _A('nutella', 'Crema spalmabile nocciole', ['nutella', 'crema di nocciole', 'crema spalmabile'], 539, 6.3, 54.4, 3.4, 41, 15, ['processato'], { cucchiaino: 8, cucchiaio: 20 }),
  _A('ketchup', 'Ketchup', ['ketchup'], 101, 1.2, 24, 0.3, 907, 15, ['processato'], { cucchiaio: 15, cucchiaino: 5 }),
  _A('salsa-soia', 'Salsa di soia', ['salsa di soia', 'soia', 'tamari'], 53, 8.1, 4.1, 0.8, 5493, 10, ['processato'], { cucchiaio: 15, cucchiaino: 5 }),
  _A('senape', 'Senape', ['senape', 'mostarda'], 66, 4, 2, 3.3, 1100, 10, [], { cucchiaino: 5, cucchiaio: 15 }),
  _A('aceto-balsamico', 'Aceto balsamico', ['aceto balsamico', 'balsamico', 'aceto'], 88, 0.5, 17, 0, 23, 10, [], { cucchiaio: 15, cucchiaino: 5 }),
  _A('sale', 'Sale', ['sale', 'sale fino', 'sale grosso'], 0, 0, 0, 0, 38700, 1, [], { pizzico: 0.5, cucchiaino: 6 }),
  _A('brodo', 'Brodo vegetale (dado)', ['brodo', 'brodo vegetale', 'dado', 'brodo di dado'], 5, 0.5, 0.5, 0, 300, 250, ['processato'], { tazza: 250 }),
  _A('caffe', 'Caffè espresso', ['caffe', 'espresso', 'caffe espresso', 'caffe amaro'], 9, 0.1, 1.7, 0, 14, 30, [], { pezzo: 30, tazzina: 30 }),
  _A('cappuccino', 'Cappuccino', ['cappuccino'], 40, 2.4, 3.4, 0, 35, 150, ['latticino'], { pezzo: 150, tazza: 150 }),
  _A('succo-arancia', "Succo d'arancia", ['succo d arancia', 'spremuta', 'succo di frutta', 'succo'], 45, 0.7, 10.2, 0.2, 1, 200, [], { bicchiere: 200 }),
  _A('cola', 'Cola / bibita zuccherata', ['coca cola', 'cola', 'bibita', 'aranciata', 'the freddo'], 42, 0, 10.6, 0, 4, 330, ['processato'], { pezzo: 330, lattina: 330, bicchiere: 200, bottiglia: 500 }),
  _A('cola-zero', 'Bibita zero', ['coca zero', 'cola zero', 'bibita zero', 'coca light', 'pepsi max'], 0.3, 0, 0, 0, 10, 330, [], { pezzo: 330, lattina: 330, bicchiere: 200, bottiglia: 500 }),
  _A('birra', 'Birra', ['birra', 'birre', 'birra chiara'], 43, 0.5, 3.6, 0, 4, 330, [], { pezzo: 330, bicchiere: 330, bottiglia: 330, lattina: 330, pinta: 500 }),
  _A('vino-rosso', 'Vino rosso', ['vino', 'vino rosso'], 85, 0.1, 2.6, 0, 4, 125, [], { pezzo: 125, bicchiere: 125, calice: 125 }),
  _A('vino-bianco', 'Vino bianco', ['vino bianco'], 82, 0.1, 2.6, 0, 5, 125, [], { pezzo: 125, bicchiere: 125, calice: 125 }),
  _A('prosecco', 'Prosecco / spumante', ['prosecco', 'spumante', 'bollicine', 'champagne'], 78, 0.1, 1.5, 0, 5, 125, [], { pezzo: 125, bicchiere: 125, calice: 125 }),
  _A('superalcolico', 'Superalcolico (40%)', ['gin', 'vodka', 'whisky', 'rum', 'grappa', 'amaro', 'superalcolico'], 231, 0, 0, 0, 1, 40, [], { pezzo: 40, bicchiere: 40, bicchierino: 40 }),
  _A('spritz', 'Spritz', ['spritz', 'aperol spritz', 'aperitivo'], 115, 0, 11, 0, 5, 200, [], { bicchiere: 200, pezzo: 200 }),
);

// Grammi per le misure casalinghe quando l'alimento non ne definisce una propria.
const MISURE_DEFAULT = {
  cucchiaio: 15,
  cucchiaino: 5,
  fetta: 30,
  manciata: 30,
  tazza: 200,
  bicchiere: 200,
  vasetto: 125,
  scatoletta: 80,
  confezione: 100,
  filo: 5,
  noce: 10,
  quadratino: 5,
  misurino: 30,
  pizzico: 0.5,
  bustina: 5,
  tazzina: 30,
  bottiglia: 500,
  lattina: 330,
  calice: 125,
  bicchierino: 40,
  pinta: 500,
  pallina: 50,
};

const TAG_DISPONIBILI = ['pesce', 'pesce-azzurro', 'carne-bianca', 'carne-rossa', 'processato', 'latticino', 'verdura', 'legume', 'frutta-secca', 'cereale', 'grasso'];
