// CRUMB — ricette precaricate.
// Ogni ricetta è un elenco di ingredienti (id del database alimenti + grammi)
// per il numero di porzioni indicato. I valori nutrizionali sono calcolati,
// mai scritti a mano.
'use strict';

const RICETTE_BASE = [
  {
    id: 'r-frittata-zucchine',
    nome: 'Frittata di zucchine',
    porzioni: 1,
    ingredienti: [
      { fid: 'uova', g: 165 },
      { fid: 'zucchine', g: 200 },
      { fid: 'parmigiano', g: 15 },
      { fid: 'olio-evo', g: 5 },
    ],
  },
  {
    id: 'r-pollo-cicoria',
    nome: 'Pollo alla piastra con cicoria',
    porzioni: 1,
    ingredienti: [
      { fid: 'pollo', g: 250 },
      { fid: 'cicoria', g: 250 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-sgombro-finocchi',
    nome: 'Sgombro al forno con finocchi',
    porzioni: 1,
    ingredienti: [
      { fid: 'sgombro', g: 200 },
      { fid: 'finocchio', g: 250 },
      { fid: 'olio-evo', g: 5 },
    ],
  },
  {
    id: 'r-alici-gratinate',
    nome: 'Alici gratinate con spinaci',
    porzioni: 1,
    ingredienti: [
      { fid: 'alici', g: 200 },
      { fid: 'parmigiano', g: 10 },
      { fid: 'spinaci', g: 250 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-bresaola-rucola',
    nome: 'Bresaola, rucola e grana',
    porzioni: 1,
    ingredienti: [
      { fid: 'bresaola', g: 80 },
      { fid: 'misticanza', g: 60 },
      { fid: 'parmigiano', g: 20 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-shirataki-tonno',
    nome: 'Shirataki con tonno e zucchine',
    porzioni: 1,
    ingredienti: [
      { fid: 'shirataki', g: 200 },
      { fid: 'tonno-naturale', g: 112 },
      { fid: 'zucchine', g: 150 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-polpette-manzo',
    nome: 'Polpette di manzo al sugo',
    porzioni: 2,
    ingredienti: [
      { fid: 'macinato-manzo', g: 400 },
      { fid: 'uova', g: 55 },
      { fid: 'parmigiano', g: 30 },
      { fid: 'pomodori', g: 300 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-zuppa-lenticchie',
    nome: 'Zuppa di lenticchie e cavolo nero',
    porzioni: 2,
    ingredienti: [
      { fid: 'lenticchie-secche', g: 120 },
      { fid: 'cavolo-nero', g: 300 },
      { fid: 'olio-evo', g: 15 },
    ],
  },
  {
    id: 'r-greco-noci',
    nome: 'Yogurt greco con noci e frutti di bosco',
    porzioni: 1,
    ingredienti: [
      { fid: 'yogurt-greco', g: 170 },
      { fid: 'noci', g: 15 },
      { fid: 'frutti-bosco', g: 50 },
    ],
  },
  {
    id: 'r-uova-avocado',
    nome: 'Uova strapazzate e avocado',
    porzioni: 1,
    ingredienti: [
      { fid: 'uova', g: 165 },
      { fid: 'avocado', g: 75 },
      { fid: 'burro', g: 5 },
    ],
  },
  {
    id: 'r-tagliata-rucola',
    nome: 'Tagliata di manzo con rucola e grana',
    porzioni: 1,
    ingredienti: [
      { fid: 'manzo', g: 220 },
      { fid: 'misticanza', g: 60 },
      { fid: 'parmigiano', g: 15 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-salmone-asparagi',
    nome: 'Salmone al forno con asparagi',
    porzioni: 1,
    ingredienti: [
      { fid: 'salmone', g: 200 },
      { fid: 'asparagi', g: 250 },
      { fid: 'olio-evo', g: 5 },
    ],
  },
  {
    id: 'r-orata-patate',
    nome: 'Orata al forno con patate',
    porzioni: 1,
    ingredienti: [
      { fid: 'orata', g: 300 },
      { fid: 'patate', g: 150 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-branzino-cartoccio',
    nome: 'Branzino al cartoccio con pomodorini',
    porzioni: 1,
    ingredienti: [
      { fid: 'branzino', g: 300 },
      { fid: 'pomodori', g: 150 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-merluzzo-zucchine',
    nome: 'Merluzzo in padella con zucchine',
    porzioni: 1,
    ingredienti: [
      { fid: 'merluzzo', g: 300 },
      { fid: 'zucchine', g: 250 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-polpo-patate',
    nome: 'Insalata di polpo e patate',
    porzioni: 1,
    ingredienti: [
      { fid: 'polpo', g: 300 },
      { fid: 'patate', g: 150 },
      { fid: 'sedano', g: 30 },
      { fid: 'olio-evo', g: 15 },
    ],
  },
  {
    id: 'r-calamari-griglia',
    nome: 'Calamari alla griglia con insalata',
    porzioni: 1,
    ingredienti: [
      { fid: 'calamari', g: 300 },
      { fid: 'misticanza', g: 100 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-cozze-pepata',
    nome: 'Impepata di cozze',
    porzioni: 1,
    ingredienti: [
      { fid: 'cozze', g: 300 },
      { fid: 'olio-evo', g: 10 },
      { fid: 'pane', g: 30 },
    ],
  },
  {
    id: 'r-spada-griglia',
    nome: 'Pesce spada alla griglia con cicoria',
    porzioni: 1,
    ingredienti: [
      { fid: 'pesce-spada', g: 220 },
      { fid: 'cicoria', g: 250 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-tonno-fagiolini',
    nome: 'Insalata di tonno, fagiolini e uova',
    porzioni: 1,
    ingredienti: [
      { fid: 'tonno-naturale', g: 112 },
      { fid: 'fagiolini', g: 200 },
      { fid: 'uova', g: 110 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-caprese',
    nome: 'Caprese',
    porzioni: 1,
    ingredienti: [
      { fid: 'mozzarella', g: 125 },
      { fid: 'pomodori', g: 200 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-caprese-bufala',
    nome: 'Caprese di bufala',
    porzioni: 1,
    ingredienti: [
      { fid: 'bufala', g: 125 },
      { fid: 'pomodori', g: 200 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-pollo-curry',
    nome: 'Pollo al curry con cavolfiore',
    porzioni: 2,
    ingredienti: [
      { fid: 'pollo', g: 500 },
      { fid: 'cavolfiore', g: 400 },
      { fid: 'panna', g: 60 },
      { fid: 'cipolla', g: 80 },
      { fid: 'olio-evo', g: 15 },
    ],
  },
  {
    id: 'r-straccetti-rucola',
    nome: 'Straccetti di pollo con rucola',
    porzioni: 1,
    ingredienti: [
      { fid: 'pollo', g: 250 },
      { fid: 'misticanza', g: 80 },
      { fid: 'olio-evo', g: 10 },
      { fid: 'aceto-balsamico', g: 10 },
    ],
  },
  {
    id: 'r-petto-tacchino-funghi',
    nome: 'Tacchino ai funghi',
    porzioni: 1,
    ingredienti: [
      { fid: 'tacchino', g: 250 },
      { fid: 'funghi', g: 200 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-hamburger-insalata',
    nome: 'Hamburger al piatto con insalata',
    porzioni: 1,
    ingredienti: [
      { fid: 'macinato-manzo', g: 200 },
      { fid: 'scamorza', g: 30 },
      { fid: 'misticanza', g: 100 },
      { fid: 'olio-evo', g: 5 },
    ],
  },
  {
    id: 'r-burger-pollo',
    nome: 'Burger di pollo e zucchine grigliate',
    porzioni: 1,
    ingredienti: [
      { fid: 'macinato-tacchino', g: 200 },
      { fid: 'zucchine', g: 250 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-scaloppine-limone',
    nome: 'Scaloppine al limone con spinaci',
    porzioni: 1,
    ingredienti: [
      { fid: 'vitello', g: 200 },
      { fid: 'farina', g: 10 },
      { fid: 'burro', g: 10 },
      { fid: 'spinaci', g: 250 },
    ],
  },
  {
    id: 'r-lonza-broccoli',
    nome: 'Lonza al forno con broccoli',
    porzioni: 1,
    ingredienti: [
      { fid: 'lonza', g: 200 },
      { fid: 'broccoli', g: 250 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-omelette-prosciutto',
    nome: 'Omelette prosciutto e formaggio',
    porzioni: 1,
    ingredienti: [
      { fid: 'uova', g: 165 },
      { fid: 'cotto', g: 40 },
      { fid: 'asiago', g: 30 },
      { fid: 'burro', g: 5 },
    ],
  },
  {
    id: 'r-uova-spinaci',
    nome: 'Uova in camicia su spinaci',
    porzioni: 1,
    ingredienti: [
      { fid: 'uova', g: 110 },
      { fid: 'spinaci', g: 250 },
      { fid: 'parmigiano', g: 15 },
      { fid: 'olio-evo', g: 5 },
    ],
  },
  {
    id: 'r-shakshuka',
    nome: 'Shakshuka',
    porzioni: 1,
    ingredienti: [
      { fid: 'uova', g: 165 },
      { fid: 'passata', g: 200 },
      { fid: 'peperoni', g: 100 },
      { fid: 'cipolla', g: 50 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-zucchine-ripiene',
    nome: 'Zucchine ripiene di carne',
    porzioni: 2,
    ingredienti: [
      { fid: 'zucchine', g: 600 },
      { fid: 'macinato-manzo', g: 300 },
      { fid: 'parmigiano', g: 30 },
      { fid: 'uova', g: 55 },
      { fid: 'passata', g: 200 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-melanzane-grigliate-feta',
    nome: 'Melanzane grigliate con feta',
    porzioni: 1,
    ingredienti: [
      { fid: 'melanzane', g: 300 },
      { fid: 'feta', g: 60 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-insalata-greca',
    nome: 'Insalata greca',
    porzioni: 1,
    ingredienti: [
      { fid: 'pomodori', g: 150 },
      { fid: 'cetrioli', g: 150 },
      { fid: 'feta', g: 80 },
      { fid: 'olive', g: 30 },
      { fid: 'cipolla', g: 30 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-pasta-tonno',
    nome: 'Pasta al tonno e pomodoro',
    porzioni: 1,
    ingredienti: [
      { fid: 'pasta', g: 80 },
      { fid: 'tonno-naturale', g: 56 },
      { fid: 'passata', g: 150 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-pasta-pomodoro',
    nome: 'Pasta al pomodoro e basilico',
    porzioni: 1,
    ingredienti: [
      { fid: 'pasta', g: 90 },
      { fid: 'passata', g: 150 },
      { fid: 'parmigiano', g: 10 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-carbonara',
    nome: 'Spaghetti alla carbonara',
    porzioni: 1,
    ingredienti: [
      { fid: 'pasta', g: 90 },
      { fid: 'guanciale', g: 40 },
      { fid: 'uova', g: 55 },
      { fid: 'pecorino', g: 20 },
    ],
  },
  {
    id: 'r-pasta-ceci',
    nome: 'Pasta e ceci',
    porzioni: 2,
    ingredienti: [
      { fid: 'pasta', g: 120 },
      { fid: 'ceci', g: 300 },
      { fid: 'passata', g: 150 },
      { fid: 'olio-evo', g: 15 },
    ],
  },
  {
    id: 'r-risotto-funghi',
    nome: 'Risotto ai funghi',
    porzioni: 2,
    ingredienti: [
      { fid: 'riso', g: 160 },
      { fid: 'funghi', g: 300 },
      { fid: 'parmigiano', g: 30 },
      { fid: 'burro', g: 15 },
      { fid: 'brodo', g: 750 },
    ],
  },
  {
    id: 'r-shirataki-gamberi',
    nome: 'Shirataki con gamberi e zucchine',
    porzioni: 1,
    ingredienti: [
      { fid: 'shirataki', g: 200 },
      { fid: 'gamberi', g: 200 },
      { fid: 'zucchine', g: 150 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-poke-salmone',
    nome: 'Poke di salmone',
    porzioni: 1,
    ingredienti: [
      { fid: 'riso', g: 70 },
      { fid: 'salmone', g: 120 },
      { fid: 'avocado', g: 60 },
      { fid: 'edamame', g: 50 },
      { fid: 'salsa-soia', g: 10 },
    ],
  },
  {
    id: 'r-porridge-proteico',
    nome: 'Porridge proteico',
    porzioni: 1,
    ingredienti: [
      { fid: 'avena', g: 40 },
      { fid: 'latte', g: 200 },
      { fid: 'proteine-whey', g: 20 },
      { fid: 'frutti-bosco', g: 50 },
    ],
  },
  {
    id: 'r-skyr-bowl',
    nome: 'Skyr con mandorle e mirtilli',
    porzioni: 1,
    ingredienti: [
      { fid: 'skyr', g: 150 },
      { fid: 'mandorle', g: 20 },
      { fid: 'frutti-bosco', g: 60 },
    ],
  },
  {
    id: 'r-pancake-proteici',
    nome: 'Pancake proteici',
    porzioni: 1,
    ingredienti: [
      { fid: 'albume', g: 150 },
      { fid: 'avena', g: 40 },
      { fid: 'proteine-whey', g: 20 },
      { fid: 'banana', g: 60 },
    ],
  },
  {
    id: 'r-toast-salmone',
    nome: 'Toast con salmone affumicato e spalmabile',
    porzioni: 1,
    ingredienti: [
      { fid: 'pane-integrale', g: 70 },
      { fid: 'salmone-affumicato', g: 60 },
      { fid: 'spalmabile', g: 30 },
    ],
  },
  {
    id: 'r-piadina-crudo',
    nome: 'Piadina crudo e stracchino',
    porzioni: 1,
    ingredienti: [
      { fid: 'piadina', g: 100 },
      { fid: 'crudo', g: 50 },
      { fid: 'stracchino', g: 50 },
      { fid: 'misticanza', g: 20 },
    ],
  },
  {
    id: 'r-minestrone-parmigiano',
    nome: 'Minestrone con parmigiano',
    porzioni: 1,
    ingredienti: [
      { fid: 'minestrone', g: 350 },
      { fid: 'parmigiano', g: 15 },
      { fid: 'olio-evo', g: 5 },
    ],
  },
  {
    id: 'r-vellutata-zucca',
    nome: 'Vellutata di zucca con ricotta',
    porzioni: 2,
    ingredienti: [
      { fid: 'zucca', g: 600 },
      { fid: 'patate', g: 150 },
      { fid: 'ricotta', g: 100 },
      { fid: 'olio-evo', g: 10 },
      { fid: 'brodo', g: 400 },
    ],
  },
  {
    id: 'r-chili',
    nome: 'Chili con carne',
    porzioni: 3,
    ingredienti: [
      { fid: 'macinato-manzo', g: 500 },
      { fid: 'fagioli', g: 400 },
      { fid: 'passata', g: 400 },
      { fid: 'cipolla', g: 100 },
      { fid: 'peperoni', g: 200 },
      { fid: 'olio-evo', g: 15 },
    ],
  },
  {
    id: 'r-tofu-verdure',
    nome: 'Tofu saltato con verdure',
    porzioni: 1,
    ingredienti: [
      { fid: 'tofu', g: 200 },
      { fid: 'peperoni', g: 150 },
      { fid: 'broccoli', g: 150 },
      { fid: 'salsa-soia', g: 10 },
      { fid: 'olio-evo', g: 10 },
    ],
  },
  {
    id: 'r-tartare',
    nome: 'Tartare di manzo',
    porzioni: 1,
    ingredienti: [
      { fid: 'manzo', g: 180 },
      { fid: 'olio-evo', g: 10 },
      { fid: 'senape', g: 5 },
      { fid: 'misticanza', g: 50 },
    ],
  },
];
