// CRUMB — ricette precaricate.
// Ogni ricetta: ingredienti (id del database alimenti + grammi per TUTTE le porzioni),
// tempo in minuti, procedimento (max 4 righe), tag manuali.
// I macro non si scrivono mai a mano: li calcola l'app sommando gli ingredienti.
// Tag calcolati dall'app: proteico, fibra-alta, sodio-basso, pesce-azzurro, legumi, veloce.
// Tag manuali (non deducibili dai numeri): batch, senza-cottura.
'use strict';

const _R = (id, nome, porzioni, tempo, tag, ingredienti, procedimento) => ({
  id, nome, porzioni, tempo, tag,
  ingredienti: ingredienti.map(([fid, g]) => ({ fid, g })),
  procedimento,
});

const RICETTE_BASE = [
  // — Dalla specifica
  _R('r-pollo-lesso-batch', 'Pollo lesso in batch', 4, 50, ['batch'],
    [['pollo', 1000], ['carote', 150], ['sedano', 100], ['cipolla', 100]],
    ['Metti petti, carota, sedano e cipolla in acqua fredda salata.', 'Porta a bollore e cuoci 25 minuti a fuoco basso.', 'Fai raffreddare nel brodo, poi sfilaccia o taglia a fette.', 'In frigo, in un contenitore chiuso, dura 3 giorni.']),
  _R('r-polpettone-parmigiano', 'Polpettone con parmigiano (senza mollica)', 4, 60, ['batch'],
    [['macinato-manzo', 800], ['uova', 110], ['parmigiano', 80], ['olio-evo', 10]],
    ['Impasta macinato, uova e parmigiano: il formaggio sostituisce la mollica.', 'Forma un filone, ungi con l’olio e chiudi nella carta forno.', 'Forno a 180 °C per 45 minuti.', 'Affettato a freddo dura 3 giorni in frigo.']),
  _R('r-sgombro-cicoria', 'Sgombro con cicoria ripassata', 1, 25, [],
    [['sgombro', 200], ['cicoria', 300], ['olio-evo', 10]],
    ['Lessa la cicoria 8 minuti, scolala e strizzala.', 'Ripassala in padella con olio e aglio.', 'Cuoci lo sgombro in padella o al forno, 5 minuti per lato.']),
  _R('r-lenticchie-uova', 'Lenticchie con uova in camicia', 1, 15, [],
    [['lenticchie', 200], ['uova', 110], ['spinaci', 100], ['olio-evo', 5]],
    ['Scalda le lenticchie già cotte con gli spinaci per 3 minuti.', 'Porta l’acqua a sfiorare il bollore, crea un vortice e cala un uovo alla volta.', 'Scola dopo 3 minuti e servi sulle lenticchie con l’olio a crudo.']),
  _R('r-frittata-zucchine', 'Frittata di zucchine', 1, 20, [],
    [['uova', 165], ['zucchine', 200], ['parmigiano', 15], ['olio-evo', 5]],
    ['Taglia le zucchine a rondelle e saltale in padella con l’olio per 6 minuti.', 'Sbatti le uova con il parmigiano e versale sulle zucchine.', 'Cuoci coperto a fuoco basso 8 minuti, poi gira con un piatto.']),
  _R('r-ceci-pollo', 'Insalata di ceci e pollo', 1, 10, ['senza-cottura'],
    [['ceci', 150], ['pollo', 200], ['pomodori', 100], ['misticanza', 50], ['olio-evo', 10]],
    ['Usa pollo già cotto (anche il lesso in batch) tagliato a dadini.', 'Sciacqua i ceci in scatola e scolali bene.', 'Unisci tutto con pomodori e insalata, condisci con olio e limone.']),
  _R('r-branzino-verdure', 'Branzino al forno con verdure', 1, 35, [],
    [['branzino', 300], ['zucchine', 150], ['peperoni', 150], ['olio-evo', 10]],
    ['Taglia zucchine e peperoni a tocchetti e mettili in teglia con metà olio.', 'Adagia sopra il branzino pulito, sale, limone e il resto dell’olio.', 'Forno a 200 °C per 25 minuti.']),
  _R('r-uova-sode-batch', 'Uova sode in batch', 6, 15, ['batch'],
    [['uova', 660]],
    ['Metti 12 uova in acqua fredda e porta a bollore.', 'Da quando bolle conta 9 minuti, poi passale in acqua e ghiaccio.', 'Tienile col guscio in frigo: durano 3 giorni (anche di più).']),
  _R('r-pollo-melanzane', 'Pollo e melanzane in umido', 2, 40, ['batch'],
    [['pollo', 450], ['melanzane', 400], ['passata', 300], ['cipolla', 60], ['olio-evo', 15]],
    ['Rosola la cipolla nell’olio, aggiungi il pollo a pezzi e dora 5 minuti.', 'Unisci melanzane a cubetti e passata, sale e basilico.', 'Cuoci coperto 25 minuti. Dura 3 giorni in frigo.']),
  _R('r-shirataki-ricotta', 'Shirataki con zucchine e ricotta', 1, 15, [],
    [['shirataki', 200], ['zucchine', 200], ['ricotta', 100], ['parmigiano', 15], ['olio-evo', 5]],
    ['Sciacqua bene gli shirataki e asciugali in padella senza grassi per 3 minuti.', 'Salta le zucchine a julienne con l’olio per 5 minuti.', 'Spegni, unisci ricotta, parmigiano e gli shirataki, mescola.']),

  // — Pesce
  _R('r-sgombro-finocchi', 'Sgombro al forno con finocchi', 1, 30, [],
    [['sgombro', 200], ['finocchio', 250], ['olio-evo', 5]],
    ['Affetta i finocchi sottili e mettili in teglia con l’olio.', 'Adagia i filetti di sgombro sopra, sale e pepe.', 'Forno a 200 °C per 20 minuti.']),
  _R('r-alici-gratinate', 'Alici gratinate con spinaci', 1, 25, [],
    [['alici', 200], ['parmigiano', 10], ['spinaci', 250], ['olio-evo', 10]],
    ['Apri le alici a libro e disponile in teglia.', 'Cospargi di parmigiano e metà olio, forno a 200 °C per 12 minuti.', 'Nel frattempo salta gli spinaci con il resto dell’olio.']),
  _R('r-salmone-asparagi', 'Salmone al forno con asparagi', 1, 25, [],
    [['salmone', 200], ['asparagi', 250], ['olio-evo', 5]],
    ['Elimina la parte dura degli asparagi e mettili in teglia con l’olio.', 'Aggiungi il trancio di salmone, sale e limone.', 'Forno a 200 °C per 15–18 minuti.']),
  _R('r-orata-patate', 'Orata al forno con patate', 1, 45, [],
    [['orata', 300], ['patate', 150], ['olio-evo', 10]],
    ['Taglia le patate a fette sottili e infornale 15 minuti a 200 °C con metà olio.', 'Aggiungi l’orata pulita, sale, rosmarino e il resto dell’olio.', 'Continua per 20–25 minuti.']),
  _R('r-branzino-cartoccio', 'Branzino al cartoccio con pomodorini', 1, 30, [],
    [['branzino', 300], ['pomodori', 150], ['olio-evo', 10]],
    ['Metti il branzino su carta forno con pomodorini tagliati, olio e origano.', 'Chiudi bene il cartoccio.', 'Forno a 200 °C per 20 minuti.']),
  _R('r-merluzzo-zucchine', 'Merluzzo in padella con zucchine', 1, 20, [],
    [['merluzzo', 300], ['zucchine', 250], ['olio-evo', 10]],
    ['Salta le zucchine a rondelle con l’olio per 6 minuti.', 'Aggiungi i filetti di merluzzo, copri e cuoci 8 minuti.', 'Sale, pepe e prezzemolo alla fine.']),
  _R('r-polpo-patate', 'Insalata di polpo e patate', 1, 60, [],
    [['polpo', 300], ['patate', 150], ['sedano', 30], ['olio-evo', 15]],
    ['Cuoci il polpo in acqua bollente 40–45 minuti, poi lascialo intiepidire nell’acqua.', 'Lessa le patate a cubetti per 12 minuti.', 'Taglia il polpo e condisci tutto con sedano, olio, limone e prezzemolo.']),
  _R('r-calamari-griglia', 'Calamari alla griglia con insalata', 1, 15, [],
    [['calamari', 300], ['misticanza', 100], ['olio-evo', 10]],
    ['Pulisci i calamari e incidili a rete.', 'Griglia sulla piastra rovente 2–3 minuti per lato.', 'Servi sull’insalata con olio e limone.']),
  _R('r-cozze-pepata', 'Impepata di cozze', 1, 20, [],
    [['cozze', 300], ['olio-evo', 10], ['pane', 30]],
    ['Pulisci le cozze e mettile in pentola con olio e aglio.', 'Copri e cuoci a fuoco alto 5–6 minuti finché si aprono.', 'Abbondante pepe e prezzemolo, servi col pane.']),
  _R('r-spada-griglia', 'Pesce spada alla griglia con cicoria', 1, 20, [],
    [['pesce-spada', 220], ['cicoria', 250], ['olio-evo', 10]],
    ['Lessa la cicoria 8 minuti e ripassala con metà olio.', 'Griglia il pesce spada 3 minuti per lato.', 'Condisci con il resto dell’olio, limone e origano.']),
  _R('r-tonno-fagiolini', 'Insalata di tonno, fagiolini e uova', 1, 15, [],
    [['tonno-naturale', 112], ['fagiolini', 200], ['uova', 110], ['olio-evo', 10]],
    ['Lessa i fagiolini 8 minuti e le uova 9 minuti.', 'Raffredda tutto sotto l’acqua fredda.', 'Unisci il tonno sgocciolato e condisci con olio e limone.']),
  _R('r-shirataki-tonno', 'Shirataki con tonno e zucchine', 1, 15, [],
    [['shirataki', 200], ['tonno-naturale', 112], ['zucchine', 150], ['olio-evo', 10]],
    ['Sciacqua gli shirataki e asciugali in padella senza grassi.', 'Salta le zucchine a julienne con l’olio per 5 minuti.', 'Unisci il tonno sgocciolato e gli shirataki, due minuti e servi.']),
  _R('r-shirataki-gamberi', 'Shirataki con gamberi e zucchine', 1, 15, [],
    [['shirataki', 200], ['gamberi', 200], ['zucchine', 150], ['olio-evo', 10]],
    ['Sciacqua gli shirataki e asciugali in padella senza grassi.', 'Salta zucchine e gamberi con l’olio e aglio per 5 minuti.', 'Unisci gli shirataki, prezzemolo e servi.']),
  _R('r-poke-salmone', 'Poke di salmone', 1, 25, [],
    [['riso', 70], ['salmone', 120], ['avocado', 60], ['edamame', 50], ['salsa-soia', 10]],
    ['Cuoci il riso e lascialo raffreddare.', 'Taglia salmone (abbattuto) e avocado a cubetti.', 'Componi la ciotola con edamame e condisci con salsa di soia.']),
  _R('r-toast-salmone', 'Toast con salmone affumicato e spalmabile', 1, 5, [],
    [['pane-integrale', 70], ['salmone-affumicato', 60], ['spalmabile', 30]],
    ['Tosta il pane.', 'Spalma il formaggio e copri con il salmone.', 'Pepe ed erba cipollina se c’è.']),

  // — Carne
  _R('r-pollo-cicoria', 'Pollo alla piastra con cicoria', 1, 20, [],
    [['pollo', 250], ['cicoria', 250], ['olio-evo', 10]],
    ['Lessa la cicoria 8 minuti e ripassala con metà olio.', 'Cuoci il petto sulla piastra rovente 4–5 minuti per lato.', 'Condisci con il resto dell’olio, sale e limone.']),
  _R('r-pollo-curry', 'Pollo al curry con cavolfiore', 2, 35, ['batch'],
    [['pollo', 500], ['cavolfiore', 400], ['panna', 60], ['cipolla', 80], ['olio-evo', 15]],
    ['Rosola la cipolla nell’olio, aggiungi il pollo a cubetti e 2 cucchiaini di curry.', 'Unisci le cimette di cavolfiore e mezzo bicchiere d’acqua.', 'Copri e cuoci 20 minuti, poi aggiungi la panna. Dura 3 giorni.']),
  _R('r-straccetti-rucola', 'Straccetti di pollo con rucola', 1, 12, [],
    [['pollo', 250], ['misticanza', 80], ['olio-evo', 10], ['aceto-balsamico', 10]],
    ['Taglia il pollo a listarelle sottili.', 'Saltalo in padella rovente con l’olio per 5–6 minuti.', 'Servi sulla rucola con l’aceto balsamico.']),
  _R('r-petto-tacchino-funghi', 'Tacchino ai funghi', 1, 25, [],
    [['tacchino', 250], ['funghi', 200], ['olio-evo', 10]],
    ['Trifola i funghi con olio e aglio per 8 minuti.', 'Aggiungi il tacchino a fette e cuoci 4 minuti per lato.', 'Prezzemolo e un filo d’acqua per legare.']),
  _R('r-tagliata-rucola', 'Tagliata di manzo con rucola e grana', 1, 15, [],
    [['manzo', 220], ['misticanza', 60], ['parmigiano', 15], ['olio-evo', 10]],
    ['Scalda bene la piastra e cuoci la carne 3 minuti per lato.', 'Lasciala riposare 3 minuti e tagliala a fette.', 'Servi sulla rucola con scaglie di grana e olio.']),
  _R('r-hamburger-insalata', 'Hamburger al piatto con insalata', 1, 15, [],
    [['macinato-manzo', 200], ['scamorza', 30], ['misticanza', 100], ['olio-evo', 5]],
    ['Forma l’hamburger e cuocilo sulla piastra 4 minuti per lato.', 'Negli ultimi 2 minuti appoggia sopra la scamorza e copri.', 'Servi con l’insalata condita.']),
  _R('r-burger-pollo', 'Burger di pollo e zucchine grigliate', 1, 20, [],
    [['macinato-tacchino', 200], ['zucchine', 250], ['olio-evo', 10]],
    ['Forma il burger e cuocilo sulla piastra 5 minuti per lato.', 'Griglia le zucchine a fette sottili.', 'Condisci le zucchine con olio, menta e sale.']),
  _R('r-polpette-manzo', 'Polpette di manzo al sugo', 2, 35, ['batch'],
    [['macinato-manzo', 400], ['uova', 55], ['parmigiano', 30], ['pomodori', 300], ['olio-evo', 10]],
    ['Impasta carne, uovo e parmigiano e forma le polpette.', 'Rosolale nell’olio 5 minuti.', 'Aggiungi i pomodori a pezzi e cuoci coperto 20 minuti.']),
  _R('r-zucchine-ripiene', 'Zucchine ripiene di carne', 2, 50, ['batch'],
    [['zucchine', 600], ['macinato-manzo', 300], ['parmigiano', 30], ['uova', 55], ['passata', 200], ['olio-evo', 10]],
    ['Taglia le zucchine a metà e svuotale.', 'Riempile con carne, uovo, parmigiano e la polpa tritata.', 'In teglia con passata e olio, forno a 180 °C per 35 minuti.']),
  _R('r-scaloppine-limone', 'Scaloppine al limone con spinaci', 1, 15, [],
    [['vitello', 200], ['farina', 10], ['burro', 10], ['spinaci', 250]],
    ['Infarina le fettine e cuocile nel burro 2 minuti per lato.', 'Sfuma con il succo di mezzo limone e un goccio d’acqua.', 'Salta gli spinaci nella stessa padella.']),
  _R('r-lonza-broccoli', 'Lonza al forno con broccoli', 1, 35, [],
    [['lonza', 200], ['broccoli', 250], ['olio-evo', 10]],
    ['Metti lonza e cimette di broccoli in teglia con olio, sale e rosmarino.', 'Forno a 200 °C per 25 minuti.', 'Lascia riposare la carne 5 minuti prima di tagliarla.']),
  _R('r-bresaola-rucola', 'Bresaola, rucola e grana', 1, 5, ['senza-cottura'],
    [['bresaola', 80], ['misticanza', 60], ['parmigiano', 20], ['olio-evo', 10]],
    ['Stendi la bresaola nel piatto.', 'Copri con rucola e scaglie di grana.', 'Olio e limone.']),
  _R('r-tartare', 'Tartare di manzo', 1, 10, ['senza-cottura'],
    [['manzo', 180], ['olio-evo', 10], ['senape', 5], ['misticanza', 50]],
    ['Trita la carne al coltello.', 'Condisci con olio, senape, sale e pepe.', 'Servi subito con l’insalata.']),
  _R('r-chili', 'Chili con carne', 3, 50, ['batch'],
    [['macinato-manzo', 500], ['fagioli', 400], ['passata', 400], ['cipolla', 100], ['peperoni', 200], ['olio-evo', 15]],
    ['Rosola cipolla e peperoni nell’olio, poi la carne finché è dorata.', 'Aggiungi passata, fagioli, cumino e paprika.', 'Cuoci a fuoco basso 30 minuti. Dura 3 giorni.']),

  // — Uova e latticini
  _R('r-uova-avocado', 'Uova strapazzate e avocado', 1, 8, [],
    [['uova', 165], ['avocado', 75], ['burro', 5]],
    ['Sciogli il burro a fuoco basso e versa le uova sbattute.', 'Mescola piano per 3 minuti, togli dal fuoco ancora morbide.', 'Servi con l’avocado a fette.']),
  _R('r-omelette-prosciutto', 'Omelette prosciutto e formaggio', 1, 10, [],
    [['uova', 165], ['cotto', 40], ['asiago', 30], ['burro', 5]],
    ['Sbatti le uova e versale nel burro caldo.', 'Quando il fondo è rappreso metti prosciutto e formaggio su metà.', 'Chiudi a mezzaluna e cuoci 1 minuto.']),
  _R('r-uova-spinaci', 'Uova in camicia su spinaci', 1, 12, [],
    [['uova', 110], ['spinaci', 250], ['parmigiano', 15], ['olio-evo', 5]],
    ['Salta gli spinaci con l’olio per 3 minuti.', 'Cuoci le uova in camicia 3 minuti nell’acqua che sfiora il bollore.', 'Servi sugli spinaci con il parmigiano.']),
  _R('r-shakshuka', 'Shakshuka', 1, 25, [],
    [['uova', 165], ['passata', 200], ['peperoni', 100], ['cipolla', 50], ['olio-evo', 10]],
    ['Stufa cipolla e peperoni nell’olio per 8 minuti.', 'Aggiungi passata, cumino e paprika, cuoci 5 minuti.', 'Fai tre conche, rompi le uova e cuoci coperto 6–8 minuti.']),
  _R('r-caprese', 'Caprese', 1, 5, ['senza-cottura'],
    [['mozzarella', 125], ['pomodori', 200], ['olio-evo', 10]],
    ['Affetta mozzarella e pomodori.', 'Alternali nel piatto con basilico.', 'Olio, sale e origano.']),
  _R('r-caprese-bufala', 'Caprese di bufala', 1, 5, ['senza-cottura'],
    [['bufala', 125], ['pomodori', 200], ['olio-evo', 10]],
    ['Affetta bufala e pomodori.', 'Alternali nel piatto con basilico.', 'Olio e sale.']),
  _R('r-greco-noci', 'Yogurt greco con noci e frutti di bosco', 1, 3, ['senza-cottura'],
    [['yogurt-greco', 170], ['noci', 15], ['frutti-bosco', 50]],
    ['Versa lo yogurt in una ciotola.', 'Aggiungi noci spezzate e frutti di bosco.']),
  _R('r-skyr-bowl', 'Skyr con mandorle e mirtilli', 1, 3, ['senza-cottura'],
    [['skyr', 150], ['mandorle', 20], ['frutti-bosco', 60]],
    ['Versa lo skyr in una ciotola.', 'Aggiungi mandorle e mirtilli.']),
  _R('r-porridge-proteico', 'Porridge proteico', 1, 8, [],
    [['avena', 40], ['latte', 200], ['proteine-whey', 20], ['frutti-bosco', 50]],
    ['Cuoci avena e latte a fuoco basso 5 minuti mescolando.', 'Spegni e incorpora le proteine in polvere.', 'Completa con i frutti di bosco.']),
  _R('r-pancake-proteici', 'Pancake proteici', 1, 15, [],
    [['albume', 150], ['avena', 40], ['proteine-whey', 20], ['banana', 60]],
    ['Frulla albumi, avena, proteine e banana.', 'Cuoci a cucchiaiate in padella antiaderente, 2 minuti per lato.']),
  _R('r-melanzane-grigliate-feta', 'Melanzane grigliate con feta', 1, 20, [],
    [['melanzane', 300], ['feta', 60], ['olio-evo', 10]],
    ['Griglia le melanzane a fette 3 minuti per lato.', 'Condiscile con olio, menta e sale.', 'Sbriciola sopra la feta.']),
  _R('r-insalata-greca', 'Insalata greca', 1, 10, ['senza-cottura'],
    [['pomodori', 150], ['cetrioli', 150], ['feta', 80], ['olive', 30], ['cipolla', 30], ['olio-evo', 10]],
    ['Taglia pomodori, cetrioli e cipolla.', 'Aggiungi olive e feta a cubetti.', 'Olio e origano.']),

  // — Legumi, cereali, zuppe
  _R('r-zuppa-lenticchie', 'Zuppa di lenticchie e cavolo nero', 2, 45, ['batch'],
    [['lenticchie-secche', 120], ['cavolo-nero', 300], ['olio-evo', 15]],
    ['Sciacqua le lenticchie e mettile in pentola con 1 litro d’acqua.', 'Dopo 15 minuti aggiungi il cavolo nero a striscioline.', 'Cuoci altri 20 minuti, olio a crudo. Dura 3 giorni.']),
  _R('r-pasta-ceci', 'Pasta e ceci', 2, 30, [],
    [['pasta', 120], ['ceci', 300], ['passata', 150], ['olio-evo', 15]],
    ['Scalda ceci e passata con olio e rosmarino per 10 minuti.', 'Frulla metà dei ceci per addensare, aggiungi acqua calda.', 'Cuoci la pasta direttamente nella zuppa.']),
  _R('r-tofu-verdure', 'Tofu saltato con verdure', 1, 15, [],
    [['tofu', 200], ['peperoni', 150], ['broccoli', 150], ['salsa-soia', 10], ['olio-evo', 10]],
    ['Taglia il tofu a cubetti e rosolalo nell’olio finché è dorato.', 'Aggiungi le verdure e salta 6–7 minuti.', 'Sfuma con la salsa di soia.']),
  _R('r-minestrone-parmigiano', 'Minestrone con parmigiano', 1, 10, [],
    [['minestrone', 350], ['parmigiano', 15], ['olio-evo', 5]],
    ['Scalda il minestrone (anche surgelato) 8 minuti.', 'Servi con parmigiano e olio a crudo.']),
  _R('r-vellutata-zucca', 'Vellutata di zucca con ricotta', 2, 35, [],
    [['zucca', 600], ['patate', 150], ['ricotta', 100], ['olio-evo', 10], ['brodo', 400]],
    ['Cuoci zucca e patate a cubetti nel brodo per 25 minuti.', 'Frulla fino a crema.', 'Servi con una cucchiaiata di ricotta e olio.']),
  _R('r-pasta-tonno', 'Pasta al tonno e pomodoro', 1, 15, [],
    [['pasta', 80], ['tonno-naturale', 56], ['passata', 150], ['olio-evo', 10]],
    ['Scalda passata e olio 5 minuti, aggiungi il tonno sgocciolato.', 'Cuoci la pasta e saltala nel sugo.']),
  _R('r-pasta-pomodoro', 'Pasta al pomodoro e basilico', 1, 15, [],
    [['pasta', 90], ['passata', 150], ['parmigiano', 10], ['olio-evo', 10]],
    ['Cuoci la passata con olio e basilico per 10 minuti.', 'Cuoci la pasta, saltala nel sugo e completa col parmigiano.']),
  _R('r-carbonara', 'Spaghetti alla carbonara', 1, 15, [],
    [['pasta', 90], ['guanciale', 40], ['uova', 55], ['pecorino', 20]],
    ['Rosola il guanciale a listarelle senza olio.', 'Sbatti uovo e pecorino con pepe.', 'Scola la pasta, uniscila al guanciale e, a fuoco spento, al composto d’uovo.']),
  _R('r-risotto-funghi', 'Risotto ai funghi', 2, 30, [],
    [['riso', 160], ['funghi', 300], ['parmigiano', 30], ['burro', 15], ['brodo', 750]],
    ['Trifola i funghi, poi tosta il riso nella stessa pentola.', 'Aggiungi il brodo caldo poco alla volta per 17 minuti.', 'Manteca a fuoco spento con burro e parmigiano.']),
  _R('r-piadina-crudo', 'Piadina crudo e stracchino', 1, 5, [],
    [['piadina', 100], ['crudo', 50], ['stracchino', 50], ['misticanza', 20]],
    ['Scalda la piadina in padella 1 minuto per lato.', 'Farcisci con stracchino, crudo e rucola.']),
];
