// CRUMB — ricette precaricate.
// Ogni ricetta: ingredienti (id del database alimenti + grammi per TUTTE le porzioni),
// tempo in minuti, procedimento (max 4 righe), tag manuali.
// I macro non si scrivono mai a mano: li calcola l'app sommando gli ingredienti.
// Tag calcolati dall'app: proteico, fibra-alta, sodio-basso, pesce-azzurro, legumi, veloce.
// Tag manuali (non deducibili dai numeri): batch, senza-cottura.
'use strict';

const _R = (id, nome, porzioni, tempo, tag, ingredienti, procedimento) => ({
  id, nome, porzioni, tempo, tag,
  ingredienti: ingredienti.map(([fid, g]) => ({ fid, g })),
  procedimento,
});

const RICETTE_BASE = [
  // — Dalla specifica
  _R('r-pollo-lesso-batch', 'Pollo lesso in batch', 4, 50, ['batch'],
    [['pollo', 1000], ['carote', 150], ['sedano', 100], ['cipolla', 100]],
    ['Metti petti, carota, sedano e cipolla in acqua fredda salata.', 'Porta a bollore e cuoci 25 minuti a fuoco basso.', 'Fai raffreddare nel brodo, poi sfilaccia o taglia a fette.', 'In frigo, in un contenitore chiuso, dura 3 giorni.']),
  _R('r-polpettone-parmigiano', 'Polpettone con parmigiano (senza mollica)', 4, 60, ['batch'],
    [['macinato-manzo', 800], ['uova', 110], ['parmigiano', 80], ['olio-evo', 10]],
    ['Impasta macinato, uova e parmigiano: il formaggio sostituisce la mollica.', 'Forma un filone, ungi con l’olio e chiudi nella carta forno.', 'Forno a 180 °C per 45 minuti.', 'Affettato a freddo dura 3 giorni in frigo.']),
  _R('r-sgombro-cicoria', 'Sgombro con cicoria ripassata', 1, 25, [],
    [['sgombro', 200], ['cicoria', 300], ['olio-evo', 10]],
    ['Lessa la cicoria 8 minuti, scolala e strizzala.', 'Ripassala in padella con olio e aglio.', 'Cuoci lo sgombro in padella o al forno, 5 minuti per lato.']),
  _R('r-lenticchie-uova', 'Lenticchie con uova in camicia', 1, 15, [],
    [['lenticchie', 200], ['uova', 110], ['spinaci', 100], ['olio-evo', 5]],
    ['Scalda le lenticchie già cotte con gli spinaci per 3 minuti.', 'Porta l’acqua a sfiorare il bollore, crea un vortice e cala un uovo alla volta.', 'Scola dopo 3 minuti e servi sulle lenticchie con l’olio a crudo.']),
  _R('r-frittata-zucchine', 'Frittata di zucchine', 1, 20, [],
    [['uova', 165], ['zucchine', 200], ['parmigiano', 15], ['olio-evo', 5]],
    ['Taglia le zucchine a rondelle e saltale in padella con l’olio per 6 minuti.', 'Sbatti le uova con il parmigiano e versale sulle zucchine.', 'Cuoci coperto a fuoco basso 8 minuti, poi gira con un piatto.']),
  _R('r-ceci-pollo', 'Insalata di ceci e pollo', 1, 10, ['senza-cottura'],
    [['ceci', 150], ['pollo', 200], ['pomodori', 100], ['misticanza', 50], ['olio-evo', 10]],
    ['Usa pollo già cotto (anche il lesso in batch) tagliato a dadini.', 'Sciacqua i ceci in scatola e scolali bene.', 'Unisci tutto con pomodori e insalata, condisci con olio e limone.']),
  _R('r-branzino-verdure', 'Branzino al forno con verdure', 1, 35, [],
    [['branzino', 300], ['zucchine', 150], ['peperoni', 150], ['olio-evo', 10]],
    ['Taglia zucchine e peperoni a tocchetti e mettili in teglia con metà olio.', 'Adagia sopra il branzino pulito, sale, limone e il resto dell’olio.', 'Forno a 200 °C per 25 minuti.']),
  _R('r-uova-sode-batch', 'Uova sode in batch', 6, 15, ['batch'],
    [['uova', 660]],
    ['Metti 12 uova in acqua fredda e porta a bollore.', 'Da quando bolle conta 9 minuti, poi passale in acqua e ghiaccio.', 'Tienile col guscio in frigo: durano 3 giorni (anche di più).']),
  _R('r-pollo-melanzane', 'Pollo e melanzane in umido', 2, 40, ['batch'],
    [['pollo', 450], ['melanzane', 400], ['passata', 300], ['cipolla', 60], ['olio-evo', 15]],
    ['Rosola la cipolla nell’olio, aggiungi il pollo a pezzi e dora 5 minuti.', 'Unisci melanzane a cubetti e passata, sale e basilico.', 'Cuoci coperto 25 minuti. Dura 3 giorni in frigo.']),
  _R('r-shirataki-ricotta', 'Shirataki con zucchine e ricotta', 1, 15, [],
    [['shirataki', 200], ['zucchine', 200], ['ricotta', 100], ['parmigiano', 15], ['olio-evo', 5]],
    ['Sciacqua bene gli shirataki e asciugali in padella senza grassi per 3 minuti.', 'Salta le zucchine a julienne con l’olio per 5 minuti.', 'Spegni, unisci ricotta, parmigiano e gli shirataki, mescola.']),

  // — Pesce
  _R('r-sgombro-finocchi', 'Sgombro al forno con finocchi', 1, 30, [],
    [['sgombro', 200], ['finocchio', 250], ['olio-evo', 5]],
    ['Affetta i finocchi sottili e mettili in teglia con l’olio.', 'Adagia i filetti di sgombro sopra, sale e pepe.', 'Forno a 200 °C per 20 minuti.']),
  _R('r-alici-gratinate', 'Alici gratinate con spinaci', 1, 25, [],
    [['alici', 200], ['parmigiano', 10], ['spinaci', 250], ['olio-evo', 10]],
    ['Apri le alici a libro e disponile in teglia.', 'Cospargi di parmigiano e metà olio, forno a 200 °C per 12 minuti.', 'Nel frattempo salta gli spinaci con il resto dell’olio.']),
  _R('r-salmone-asparagi', 'Salmone al forno con asparagi', 1, 25, [],
    [['salmone', 200], ['asparagi', 250], ['olio-evo', 5]],
    ['Elimina la parte dura degli asparagi e mettili in teglia con l’olio.', 'Aggiungi il trancio di salmone, sale e limone.', 'Forno a 200 °C per 15–18 minuti.']),
  _R('r-orata-patate', 'Orata al forno con patate', 1, 45, [],
    [['orata', 300], ['patate', 150], ['olio-evo', 10]],
    ['Taglia le patate a fette sottili e infornale 15 minuti a 200 °C con metà olio.', 'Aggiungi l’orata pulita, sale, rosmarino e il resto dell’olio.', 'Continua per 20–25 minuti.']),
  _R('r-branzino-cartoccio', 'Branzino al cartoccio con pomodorini', 1, 30, [],
    [['branzino', 300], ['pomodori', 150], ['olio-evo', 10]],
    ['Metti il branzino su carta forno con pomodorini tagliati, olio e origano.', 'Chiudi bene il cartoccio.', 'Forno a 200 °C per 20 minuti.']),
  _R('r-merluzzo-zucchine', 'Merluzzo in padella con zucchine', 1, 20, [],
    [['merluzzo', 300], ['zucchine', 250], ['olio-evo', 10]],
    ['Salta le zucchine a rondelle con l’olio per 6 minuti.', 'Aggiungi i filetti di merluzzo, copri e cuoci 8 minuti.', 'Sale, pepe e prezzemolo alla fine.']),
  _R('r-polpo-patate', 'Insalata di polpo e patate', 1, 60, [],
    [['polpo', 300], ['patate', 150], ['sedano', 30], ['olio-evo', 15]],
    ['Cuoci il polpo in acqua bollente 40–45 minuti, poi lascialo intiepidire nell’acqua.', 'Lessa le patate a cubetti per 12 minuti.', 'Taglia il polpo e condisci tutto con sedano, olio, limone e prezzemolo.']),
  _R('r-calamari-griglia', 'Calamari alla griglia con insalata', 1, 15, [],
    [['calamari', 300], ['misticanza', 100], ['olio-evo', 10]],
    ['Pulisci i calamari e incidili a rete.', 'Griglia sulla piastra rovente 2–3 minuti per lato.', 'Servi sull’insalata con olio e limone.']),
  _R('r-cozze-pepata', 'Impepata di cozze', 1, 20, [],
    [['cozze', 300], ['olio-evo', 10], ['pane', 30]],
    ['Pulisci le cozze e mettile in pentola con olio e aglio.', 'Copri e cuoci a fuoco alto 5–6 minuti finché si aprono.', 'Abbondante pepe e prezzemolo, servi col pane.']),
  _R('r-spada-griglia', 'Pesce spada alla griglia con cicoria', 1, 20, [],
    [['pesce-spada', 220], ['cicoria', 250], ['olio-evo', 10]],
    ['Lessa la cicoria 8 minuti e ripassala con metà olio.', 'Griglia il pesce spada 3 minuti per lato.', 'Condisci con il resto dell’olio, limone e origano.']),
  _R('r-tonno-fagiolini', 'Insalata di tonno, fagiolini e uova', 1, 15, [],
    [['tonno-naturale', 112], ['fagiolini', 200], ['uova', 110], ['olio-evo', 10]],
    ['Lessa i fagiolini 8 minuti e le uova 9 minuti.', 'Raffredda tutto sotto l’acqua fredda.', 'Unisci il tonno sgocciolato e condisci con olio e limone.']),
  _R('r-shirataki-tonno', 'Shirataki con tonno e zucchine', 1, 15, [],
    [['shirataki', 200], ['tonno-naturale', 112], ['zucchine', 150], ['olio-evo', 10]],
    ['Sciacqua gli shirataki e asciugali in padella senza grassi.', 'Salta le zucchine a julienne con l’olio per 5 minuti.', 'Unisci il tonno sgocciolato e gli shirataki, due minuti e servi.']),
  _R('r-shirataki-gamberi', 'Shirataki con gamberi e zucchine', 1, 15, [],
    [['shirataki', 200], ['gamberi', 200], ['zucchine', 150], ['olio-evo', 10]],
    ['Sciacqua gli shirataki e asciugali in padella senza grassi.', 'Salta zucchine e gamberi con l’olio e aglio per 5 minuti.', 'Unisci gli shirataki, prezzemolo e servi.']),
  _R('r-poke-salmone', 'Poke di salmone', 1, 25, [],
    [['riso', 70], ['salmone', 120], ['avocado', 60], ['edamame', 50], ['salsa-soia', 10]],
    ['Cuoci il riso e lascialo raffreddare.', 'Taglia salmone (abbattuto) e avocado a cubetti.', 'Componi la ciotola con edamame e condisci con salsa di soia.']),
  _R('r-toast-salmone', 'Toast con salmone affumicato e spalmabile', 1, 5, [],
    [['pane-integrale', 70], ['salmone-affumicato', 60], ['spalmabile', 30]],
    ['Tosta il pane.', 'Spalma il formaggio e copri con il salmone.', 'Pepe ed erba cipollina se c’è.']),

  // — Carne
  _R('r-pollo-cicoria', 'Pollo alla piastra con cicoria', 1, 20, [],
    [['pollo', 250], ['cicoria', 250], ['olio-evo', 10]],
    ['Lessa la cicoria 8 minuti e ripassala con metà olio.', 'Cuoci il petto sulla piastra rovente 4–5 minuti per lato.', 'Condisci con il resto dell’olio, sale e limone.']),
  _R('r-pollo-curry', 'Pollo al curry con cavolfiore', 2, 35, ['batch'],
    [['pollo', 500], ['cavolfiore', 400], ['panna', 60], ['cipolla', 80], ['olio-evo', 15]],
    ['Rosola la cipolla nell’olio, aggiungi il pollo a cubetti e 2 cucchiaini di curry.', 'Unisci le cimette di cavolfiore e mezzo bicchiere d’acqua.', 'Copri e cuoci 20 minuti, poi aggiungi la panna. Dura 3 giorni.']),
  _R('r-straccetti-rucola', 'Straccetti di pollo con rucola', 1, 12, [],
    [['pollo', 250], ['misticanza', 80], ['olio-evo', 10], ['aceto-balsamico', 10]],
    ['Taglia il pollo a listarelle sottili.', 'Saltalo in padella rovente con l’olio per 5–6 minuti.', 'Servi sulla rucola con l’aceto balsamico.']),
  _R('r-petto-tacchino-funghi', 'Tacchino ai funghi', 1, 25, [],
    [['tacchino', 250], ['funghi', 200], ['olio-evo', 10]],
    ['Trifola i funghi con olio e aglio per 8 minuti.', 'Aggiungi il tacchino a fette e cuoci 4 minuti per lato.', 'Prezzemolo e un filo d’acqua per legare.']),
  _R('r-tagliata-rucola', 'Tagliata di manzo con rucola e grana', 1, 15, [],
    [['manzo', 220], ['misticanza', 60], ['parmigiano', 15], ['olio-evo', 10]],
    ['Scalda bene la piastra e cuoci la carne 3 minuti per lato.', 'Lasciala riposare 3 minuti e tagliala a fette.', 'Servi sulla rucola con scaglie di grana e olio.']),
  _R('r-hamburger-insalata', 'Hamburger al piatto con insalata', 1, 15, [],
    [['macinato-manzo', 200], ['scamorza', 30], ['misticanza', 100], ['olio-evo', 5]],
    ['Forma l’hamburger e cuocilo sulla piastra 4 minuti per lato.', 'Negli ultimi 2 minuti appoggia sopra la scamorza e copri.', 'Servi con l’insalata condita.']),
  _R('r-burger-pollo', 'Burger di pollo e zucchine grigliate', 1, 20, [],
    [['macinato-tacchino', 200], ['zucchine', 250], ['olio-evo', 10]],
    ['Forma il burger e cuocilo sulla piastra 5 minuti per lato.', 'Griglia le zucchine a fette sottili.', 'Condisci le zucchine con olio, menta e sale.']),
  _R('r-polpette-manzo', 'Polpette di manzo al sugo', 2, 35, ['batch'],
    [['macinato-manzo', 400], ['uova', 55], ['parmigiano', 30], ['pomodori', 300], ['olio-evo', 10]],
    ['Impasta carne, uovo e parmigiano e forma le polpette.', 'Rosolale nell’olio 5 minuti.', 'Aggiungi i pomodori a pezzi e cuoci coperto 20 minuti.']),
  _R('r-zucchine-ripiene', 'Zucchine ripiene di carne', 2, 50, ['batch'],
    [['zucchine', 600], ['macinato-manzo', 300], ['parmigiano', 30], ['uova', 55], ['passata', 200], ['olio-evo', 10]],
    ['Taglia le zucchine a metà e svuotale.', 'Riempile con carne, uovo, parmigiano e la polpa tritata.', 'In teglia con passata e olio, forno a 180 °C per 35 minuti.']),
  _R('r-scaloppine-limone', 'Scaloppine al limone con spinaci', 1, 15, [],
    [['vitello', 200], ['farina', 10], ['burro', 10], ['spinaci', 250]],
    ['Infarina le fettine e cuocile nel burro 2 minuti per lato.', 'Sfuma con il succo di mezzo limone e un goccio d’acqua.', 'Salta gli spinaci nella stessa padella.']),
  _R('r-lonza-broccoli', 'Lonza al forno con broccoli', 1, 35, [],
    [['lonza', 200], ['broccoli', 250], ['olio-evo', 10]],
    ['Metti lonza e cimette di broccoli in teglia con olio, sale e rosmarino.', 'Forno a 200 °C per 25 minuti.', 'Lascia riposare la carne 5 minuti prima di tagliarla.']),
  _R('r-bresaola-rucola', 'Bresaola, rucola e grana', 1, 5, ['senza-cottura'],
    [['bresaola', 80], ['misticanza', 60], ['parmigiano', 20], ['olio-evo', 10]],
    ['Stendi la bresaola nel piatto.', 'Copri con rucola e scaglie di grana.', 'Olio e limone.']),
  _R('r-tartare', 'Tartare di manzo', 1, 10, ['senza-cottura'],
    [['manzo', 180], ['olio-evo', 10], ['senape', 5], ['misticanza', 50]],
    ['Trita la carne al coltello.', 'Condisci con olio, senape, sale e pepe.', 'Servi subito con l’insalata.']),
  _R('r-chili', 'Chili con carne', 3, 50, ['batch'],
    [['macinato-manzo', 500], ['fagioli', 400], ['passata', 400], ['cipolla', 100], ['peperoni', 200], ['olio-evo', 15]],
    ['Rosola cipolla e peperoni nell’olio, poi la carne finché è dorata.', 'Aggiungi passata, fagioli, cumino e paprika.', 'Cuoci a fuoco basso 30 minuti. Dura 3 giorni.']),

  // — Uova e latticini
  _R('r-uova-avocado', 'Uova strapazzate e avocado', 1, 8, [],
    [['uova', 165], ['avocado', 75], ['burro', 5]],
    ['Sciogli il burro a fuoco basso e versa le uova sbattute.', 'Mescola piano per 3 minuti, togli dal fuoco ancora morbide.', 'Servi con l’avocado a fette.']),
  _R('r-omelette-prosciutto', 'Omelette prosciutto e formaggio', 1, 10, [],
    [['uova', 165], ['cotto', 40], ['asiago', 30], ['burro', 5]],
    ['Sbatti le uova e versale nel burro caldo.', 'Quando il fondo è rappreso metti prosciutto e formaggio su metà.', 'Chiudi a mezzaluna e cuoci 1 minuto.']),
  _R('r-uova-spinaci', 'Uova in camicia su spinaci', 1, 12, [],
    [['uova', 110], ['spinaci', 250], ['parmigiano', 15], ['olio-evo', 5]],
    ['Salta gli spinaci con l’olio per 3 minuti.', 'Cuoci le uova in camicia 3 minuti nell’acqua che sfiora il bollore.', 'Servi sugli spinaci con il parmigiano.']),
  _R('r-shakshuka', 'Shakshuka', 1, 25, [],
    [['uova', 165], ['passata', 200], ['peperoni', 100], ['cipolla', 50], ['olio-evo', 10]],
    ['Stufa cipolla e peperoni nell’olio per 8 minuti.', 'Aggiungi passata, cumino e paprika, cuoci 5 minuti.', 'Fai tre conche, rompi le uova e cuoci coperto 6–8 minuti.']),
  _R('r-caprese', 'Caprese', 1, 5, ['senza-cottura'],
    [['mozzarella', 125], ['pomodori', 200], ['olio-evo', 10]],
    ['Affetta mozzarella e pomodori.', 'Alternali nel piatto con basilico.', 'Olio, sale e origano.']),
  _R('r-caprese-bufala', 'Caprese di bufala', 1, 5, ['senza-cottura'],
    [['bufala', 125], ['pomodori', 200], ['olio-evo', 10]],
    ['Affetta bufala e pomodori.', 'Alternali nel piatto con basilico.', 'Olio e sale.']),
  _R('r-greco-noci', 'Yogurt greco con noci e frutti di bosco', 1, 3, ['senza-cottura'],
    [['yogurt-greco', 170], ['noci', 15], ['frutti-bosco', 50]],
    ['Versa lo yogurt in una ciotola.', 'Aggiungi noci spezzate e frutti di bosco.']),
  _R('r-skyr-bowl', 'Skyr con mandorle e mirtilli', 1, 3, ['senza-cottura'],
    [['skyr', 150], ['mandorle', 20], ['frutti-bosco', 60]],
    ['Versa lo skyr in una ciotola.', 'Aggiungi mandorle e mirtilli.']),
  _R('r-porridge-proteico', 'Porridge proteico', 1, 8, [],
    [['avena', 40], ['latte', 200], ['proteine-whey', 20], ['frutti-bosco', 50]],
    ['Cuoci avena e latte a fuoco basso 5 minuti mescolando.', 'Spegni e incorpora le proteine in polvere.', 'Completa con i frutti di bosco.']),
  _R('r-pancake-proteici', 'Pancake proteici', 1, 15, [],
    [['albume', 150], ['avena', 40], ['proteine-whey', 20], ['banana', 60]],
    ['Frulla albumi, avena, proteine e banana.', 'Cuoci a cucchiaiate in padella antiaderente, 2 minuti per lato.']),
  _R('r-melanzane-grigliate-feta', 'Melanzane grigliate con feta', 1, 20, [],
    [['melanzane', 300], ['feta', 60], ['olio-evo', 10]],
    ['Griglia le melanzane a fette 3 minuti per lato.', 'Condiscile con olio, menta e sale.', 'Sbriciola sopra la feta.']),
  _R('r-insalata-greca', 'Insalata greca', 1, 10, ['senza-cottura'],
    [['pomodori', 150], ['cetrioli', 150], ['feta', 80], ['olive', 30], ['cipolla', 30], ['olio-evo', 10]],
    ['Taglia pomodori, cetrioli e cipolla.', 'Aggiungi olive e feta a cubetti.', 'Olio e origano.']),

  // — Legumi, cereali, zuppe
  _R('r-zuppa-lenticchie', 'Zuppa di lenticchie e cavolo nero', 2, 45, ['batch'],
    [['lenticchie-secche', 120], ['cavolo-nero', 300], ['olio-evo', 15]],
    ['Sciacqua le lenticchie e mettile in pentola con 1 litro d’acqua.', 'Dopo 15 minuti aggiungi il cavolo nero a striscioline.', 'Cuoci altri 20 minuti, olio a crudo. Dura 3 giorni.']),
  _R('r-pasta-ceci', 'Pasta e ceci', 2, 30, [],
    [['pasta', 120], ['ceci', 300], ['passata', 150], ['olio-evo', 15]],
    ['Scalda ceci e passata con olio e rosmarino per 10 minuti.', 'Frulla metà dei ceci per addensare, aggiungi acqua calda.', 'Cuoci la pasta direttamente nella zuppa.']),
  _R('r-tofu-verdure', 'Tofu saltato con verdure', 1, 15, [],
    [['tofu', 200], ['peperoni', 150], ['broccoli', 150], ['salsa-soia', 10], ['olio-evo', 10]],
    ['Taglia il tofu a cubetti e rosolalo nell’olio finché è dorato.', 'Aggiungi le verdure e salta 6–7 minuti.', 'Sfuma con la salsa di soia.']),
  _R('r-minestrone-parmigiano', 'Minestrone con parmigiano', 1, 10, [],
    [['minestrone', 350], ['parmigiano', 15], ['olio-evo', 5]],
    ['Scalda il minestrone (anche surgelato) 8 minuti.', 'Servi con parmigiano e olio a crudo.']),
  _R('r-vellutata-zucca', 'Vellutata di zucca con ricotta', 2, 35, [],
    [['zucca', 600], ['patate', 150], ['ricotta', 100], ['olio-evo', 10], ['brodo', 400]],
    ['Cuoci zucca e patate a cubetti nel brodo per 25 minuti.', 'Frulla fino a crema.', 'Servi con una cucchiaiata di ricotta e olio.']),
  _R('r-pasta-tonno', 'Pasta al tonno e pomodoro', 1, 15, [],
    [['pasta', 80], ['tonno-naturale', 56], ['passata', 150], ['olio-evo', 10]],
    ['Scalda passata e olio 5 minuti, aggiungi il tonno sgocciolato.', 'Cuoci la pasta e saltala nel sugo.']),
  _R('r-pasta-pomodoro', 'Pasta al pomodoro e basilico', 1, 15, [],
    [['pasta', 90], ['passata', 150], ['parmigiano', 10], ['olio-evo', 10]],
    ['Cuoci la passata con olio e basilico per 10 minuti.', 'Cuoci la pasta, saltala nel sugo e completa col parmigiano.']),
  _R('r-carbonara', 'Spaghetti alla carbonara', 1, 15, [],
    [['pasta', 90], ['guanciale', 40], ['uova', 55], ['pecorino', 20]],
    ['Rosola il guanciale a listarelle senza olio.', 'Sbatti uovo e pecorino con pepe.', 'Scola la pasta, uniscila al guanciale e, a fuoco spento, al composto d’uovo.']),
  _R('r-risotto-funghi', 'Risotto ai funghi', 2, 30, [],
    [['riso', 160], ['funghi', 300], ['parmigiano', 30], ['burro', 15], ['brodo', 750]],
    ['Trifola i funghi, poi tosta il riso nella stessa pentola.', 'Aggiungi il brodo caldo poco alla volta per 17 minuti.', 'Manteca a fuoco spento con burro e parmigiano.']),
  // — Mediterranee: cereali, legumi, pesce
  _R('r-pasta-fagioli', 'Pasta e fagioli', 2, 30, [],
    [['fagioli', 300], ['pasta', 120], ['passata', 100], ['sedano', 40], ['carote', 50], ['olio-evo', 15]],
    ['Soffriggi sedano e carota tritati nell’olio, aggiungi passata e fagioli.', 'Copri d’acqua, cuoci 10 minuti e schiaccia metà dei fagioli.', 'Cuoci la pasta nella minestra, rosmarino e pepe alla fine.']),
  _R('r-farro-ceci', 'Insalata di farro, ceci e feta', 2, 35, ['batch'],
    [['farro', 160], ['ceci', 200], ['pomodori', 200], ['cetrioli', 150], ['feta', 60], ['olio-evo', 15]],
    ['Lessa il farro 25–30 minuti e raffreddalo sotto l’acqua.', 'Unisci ceci, pomodori e cetrioli a cubetti, poi la feta.', 'Condisci con olio e limone. Dura 3 giorni in frigo.']),
  _R('r-orzotto-gamberi', 'Orzotto con zucchine e gamberi', 2, 35, [],
    [['orzo', 140], ['gamberi', 300], ['zucchine', 300], ['cipolla', 40], ['olio-evo', 15], ['brodo', 600]],
    ['Tosta l’orzo con cipolla e olio, poi cuocilo nel brodo per 25 minuti.', 'A metà cottura aggiungi le zucchine a cubetti.', 'Negli ultimi 3 minuti unisci i gamberi.']),
  _R('r-spaghetti-vongole', 'Spaghetti alle vongole', 1, 20, [],
    [['pasta', 90], ['vongole', 150], ['olio-evo', 10]],
    ['Fai aprire le vongole in padella con olio e aglio, coperte, 4 minuti.', 'Cuoci la pasta molto al dente.', 'Finisci la cottura in padella con il liquido delle vongole e prezzemolo.']),
  _R('r-pasta-sarde', 'Pasta con le sarde e finocchio', 1, 30, [],
    [['pasta', 90], ['sardine', 150], ['finocchio', 100], ['uvetta', 10], ['olio-evo', 10]],
    ['Lessa il finocchio a pezzi e usa l’acqua per la pasta.', 'Rosola le sarde pulite nell’olio con il finocchio e l’uvetta.', 'Salta la pasta nel condimento.']),
  _R('r-orecchiette-cime', 'Orecchiette con cime di rapa', 1, 25, [],
    [['pasta', 90], ['broccoli', 250], ['acciughe-olio', 8], ['olio-evo', 10]],
    ['Cuoci cime di rapa e orecchiette nella stessa acqua.', 'Sciogli le acciughe nell’olio con aglio e peperoncino.', 'Scola e salta tutto in padella.']),
  _R('r-baccala-ceci', 'Baccalà con ceci e pomodoro', 2, 35, [],
    [['baccala', 400], ['ceci', 250], ['passata', 200], ['olio-evo', 15]],
    ['Scalda passata e olio con aglio, aggiungi i ceci e cuoci 10 minuti.', 'Adagia il baccalà a pezzi, copri e cuoci 12 minuti.', 'Prezzemolo e pepe alla fine.']),
  _R('r-sgombro-patate-olive', 'Sgombro al forno con patate e olive', 1, 40, [],
    [['sgombro', 200], ['patate', 200], ['olive', 20], ['olio-evo', 10]],
    ['Inforna le patate a fette con metà olio per 15 minuti a 200 °C.', 'Aggiungi lo sgombro, le olive e il resto dell’olio.', 'Altri 15–18 minuti.']),
  _R('r-salmone-quinoa', 'Salmone con quinoa e verdure', 1, 25, [],
    [['salmone', 150], ['quinoa', 60], ['zucchine', 150], ['peperoni', 100], ['olio-evo', 5]],
    ['Cuoci la quinoa sciacquata in acqua per 15 minuti.', 'Salta zucchine e peperoni con l’olio.', 'Cuoci il salmone in padella 4 minuti per lato.']),
  _R('r-minestrone-legumi', 'Minestrone con legumi e orzo', 4, 60, ['batch'],
    [['zucca', 300], ['carote', 200], ['sedano', 100], ['cavolo-nero', 300], ['fagioli', 300], ['ceci', 200], ['orzo', 120], ['passata', 200], ['olio-evo', 20]],
    ['Metti tutte le verdure a pezzi in pentola con passata e 2 litri d’acqua.', 'Dopo 30 minuti aggiungi orzo e legumi, cuoci altri 25 minuti.', 'Olio a crudo nel piatto. Dura 3 giorni in frigo.']),
  _R('r-zuppa-farro-lenticchie', 'Zuppa di farro e lenticchie', 3, 45, ['batch'],
    [['farro', 150], ['lenticchie-secche', 150], ['carote', 150], ['sedano', 80], ['cipolla', 80], ['passata', 150], ['olio-evo', 15]],
    ['Soffriggi carota, sedano e cipolla nell’olio.', 'Aggiungi farro, lenticchie, passata e 1,5 litri d’acqua.', 'Cuoci 35 minuti a fuoco basso. Dura 3 giorni.']),
  _R('r-pollo-limone-patate', 'Pollo al limone con patate e fagiolini', 1, 40, [],
    [['pollo', 220], ['patate', 200], ['fagiolini', 150], ['olio-evo', 10]],
    ['Inforna le patate a spicchi con metà olio per 20 minuti a 200 °C.', 'Aggiungi il pollo marinato con limone e origano, altri 15 minuti.', 'Lessa i fagiolini 8 minuti e condiscili con il resto dell’olio.']),
  _R('r-farro-tacchino', 'Bowl di farro, tacchino e verdure grigliate', 1, 25, [],
    [['farro', 70], ['tacchino', 180], ['verdure-grigliate', 200], ['olio-evo', 10]],
    ['Lessa il farro (o usa quello in batch).', 'Griglia il tacchino 3 minuti per lato e taglialo a strisce.', 'Componi la ciotola con le verdure e l’olio.']),
  _R('r-riso-tonno', 'Insalata di riso integrale e tonno', 2, 35, ['batch'],
    [['riso-integrale', 160], ['tonno-naturale', 224], ['pomodori', 200], ['olive', 30], ['mozzarella-light', 125], ['olio-evo', 15]],
    ['Lessa il riso integrale 30 minuti e raffreddalo.', 'Unisci tonno, pomodori, olive e mozzarella a cubetti.', 'Condisci con l’olio. Dura 3 giorni in frigo.']),

  // — DASH: poco sodio, verdura, frutta, frutta secca, latticini magri
  _R('r-avena-yogurt-mela', 'Avena con yogurt, mela e noci', 1, 5, ['senza-cottura'],
    [['avena', 50], ['yogurt-greco', 170], ['mela', 150], ['noci', 15]],
    ['Mescola avena e yogurt, lascia riposare 5 minuti (o tutta la notte).', 'Aggiungi la mela a dadini, le noci e cannella.']),
  _R('r-pollo-quinoa-spinaci', 'Pollo, quinoa e spinaci al limone', 1, 25, [],
    [['pollo', 200], ['quinoa', 70], ['spinaci', 200], ['mandorle', 15], ['olio-evo', 5]],
    ['Cuoci la quinoa 15 minuti.', 'Cuoci il pollo sulla piastra e taglialo a strisce.', 'Salta gli spinaci, unisci tutto con limone e mandorle a lamelle.']),
  _R('r-merluzzo-patate-dolci', 'Merluzzo con patate dolci e broccoli', 1, 35, [],
    [['merluzzo', 250], ['patate-dolci', 200], ['broccoli', 200], ['olio-evo', 10]],
    ['Inforna le patate dolci a cubetti con metà olio per 20 minuti a 200 °C.', 'Aggiungi merluzzo e broccoli, il resto dell’olio e limone.', 'Altri 12–15 minuti.']),
  _R('r-insalata-lenticchie-arancia', 'Insalata di lenticchie, spinaci e arancia', 1, 10, ['senza-cottura'],
    [['lenticchie', 200], ['spinaci', 80], ['arancia', 150], ['noci', 15], ['olio-evo', 10]],
    ['Sciacqua le lenticchie già cotte.', 'Unisci spinaci crudi, arancia a spicchi e noci.', 'Olio e pepe, senza sale: basta l’arancia.']),
  _R('r-frullato-yogurt', 'Frullato di yogurt, banana e frutti di bosco', 1, 5, ['senza-cottura'],
    [['yogurt-greco', 200], ['banana', 100], ['frutti-bosco', 100], ['latte-scremato', 100]],
    ['Frulla tutto per 30 secondi.', 'Con frutti di bosco surgelati viene più denso.']),

  // — Flessitariane: legumi, tofu, uova
  _R('r-curry-ceci', 'Curry di ceci e spinaci', 3, 30, ['batch'],
    [['ceci', 500], ['spinaci', 300], ['passata', 300], ['cipolla', 80], ['yogurt-greco', 150], ['olio-evo', 15]],
    ['Rosola la cipolla nell’olio con 2 cucchiaini di curry.', 'Aggiungi ceci e passata, cuoci 15 minuti.', 'Unisci gli spinaci, spegni e completa con lo yogurt. Dura 3 giorni.']),
  _R('r-dal-lenticchie', 'Dal di lenticchie rosse', 3, 30, ['batch'],
    [['lenticchie-rosse', 250], ['passata', 200], ['cipolla', 80], ['spinaci', 200], ['olio-evo', 15]],
    ['Rosola la cipolla con curcuma e cumino.', 'Aggiungi lenticchie, passata e 700 ml d’acqua, cuoci 20 minuti.', 'Unisci gli spinaci negli ultimi 3 minuti. Dura 3 giorni.']),
  _R('r-tofu-riso-broccoli', 'Tofu, riso integrale e broccoli', 1, 25, [],
    [['tofu', 200], ['riso-integrale', 60], ['broccoli', 200], ['salsa-soia', 10], ['olio-evo', 10]],
    ['Cuoci il riso integrale (o usa quello in batch).', 'Rosola il tofu a cubetti nell’olio finché è dorato.', 'Aggiungi i broccoli sbollentati e la salsa di soia.']),
  _R('r-tempeh-bowl', 'Bowl di tempeh, quinoa ed edamame', 1, 25, [],
    [['tempeh', 120], ['quinoa', 60], ['edamame', 100], ['cappuccio', 100], ['tahina', 15]],
    ['Cuoci la quinoa 15 minuti.', 'Rosola il tempeh a fette in padella antiaderente.', 'Componi con edamame e cavolo a julienne, condisci con tahina e limone.']),
  _R('r-frittata-albumi', 'Frittata al forno di uova, albumi e verdure', 2, 30, ['batch'],
    [['uova', 220], ['albume', 300], ['zucchine', 200], ['peperoni', 150], ['parmigiano', 30]],
    ['Taglia le verdure a cubetti e mettile in teglia rivestita di carta forno.', 'Versa sopra uova, albumi e parmigiano sbattuti.', 'Forno a 180 °C per 25 minuti. Dura 3 giorni.']),
  _R('r-hummus-verdure', 'Hummus con verdure crude e pane integrale', 1, 5, ['senza-cottura'],
    [['hummus', 100], ['carote', 100], ['cetrioli', 100], ['peperoni', 100], ['pane-integrale', 50]],
    ['Taglia le verdure a bastoncini.', 'Servi con l’hummus e il pane tostato.']),
  _R('r-pasta-legumi-ricotta', 'Pasta di legumi al pomodoro e ricotta', 1, 15, [],
    [['pasta-legumi', 90], ['passata', 150], ['ricotta', 80], ['olio-evo', 5]],
    ['Scalda la passata con olio e basilico 8 minuti.', 'Cuoci la pasta di legumi (bastano 6–8 minuti).', 'Condisci e completa con la ricotta a cucchiaiate.']),

  _R('r-piadina-crudo', 'Piadina crudo e stracchino', 1, 5, [],
    [['piadina', 100], ['crudo', 50], ['stracchino', 50], ['misticanza', 20]],
    ['Scalda la piadina in padella 1 minuto per lato.', 'Farcisci con stracchino, crudo e rucola.']),
];

// Piatti comuni: composizione standard di UNA porzione, per riconoscerli quando li scrivi
// ("uova al purgatorio", "amatriciana"). Non sono ricette: niente procedimento, non compaiono
// nei suggerimenti. Scritti nel diario si scompongono negli ingredienti, modificabili.
const _P = (id, nome, alias, ingredienti) => ({ id, nome, alias, porzioni: 1, piatto: true, ingredienti: ingredienti.map(([fid, g]) => ({ fid, g })) });

const PIATTI_BASE = [
  // — Uova
  _P('p-uova-purgatorio', 'Uova al purgatorio', ['uova in purgatorio'], [['uova', 110], ['passata', 150], ['olio-evo', 10]]),
  _P('p-uova-occhio', "Uova all'occhio di bue", ['uova al tegamino', 'uovo al tegamino', 'uova occhio di bue', 'uovo all occhio di bue'], [['uova', 110], ['olio-evo', 5]]),
  _P('p-uova-strapazzate', 'Uova strapazzate', ['uovo strapazzato', 'strapazzate'], [['uova', 165], ['burro', 5]]),
  _P('p-omelette', 'Omelette', ['omelette semplice', 'omelet'], [['uova', 165], ['olio-evo', 5]]),
  _P('p-frittata', 'Frittata', ['frittata semplice', 'frittata al formaggio'], [['uova', 165], ['parmigiano', 10], ['olio-evo', 5]]),
  _P('p-uova-bacon', 'Uova e bacon', ['uova e pancetta', 'bacon e uova'], [['uova', 110], ['pancetta', 30]]),

  // — Pasta, riso, gnocchi
  _P('p-aglio-olio', 'Spaghetti aglio olio e peperoncino', ['aglio olio e peperoncino', 'pasta aglio e olio', 'spaghetti aglio e olio', 'aglio e olio'], [['pasta', 90], ['olio-evo', 15]]),
  _P('p-pasta-pomodoro', 'Pasta al pomodoro', ['pasta al sugo', 'spaghetti al pomodoro', 'pasta pomodoro', 'penne al pomodoro'], [['pasta', 90], ['passata', 150], ['parmigiano', 10], ['olio-evo', 10]]),
  _P('p-pasta-bianco', 'Pasta in bianco', ['pasta olio e parmigiano', 'pasta in bianco con parmigiano'], [['pasta', 90], ['olio-evo', 10], ['parmigiano', 10]]),
  _P('p-pasta-burro', 'Pasta al burro', ['pasta burro e parmigiano'], [['pasta', 90], ['burro', 15], ['parmigiano', 10]]),
  _P('p-amatriciana', "Pasta all'amatriciana", ['amatriciana', 'bucatini all amatriciana', 'spaghetti all amatriciana'], [['pasta', 90], ['guanciale', 40], ['passata', 120], ['pecorino', 15]]),
  _P('p-gricia', 'Pasta alla gricia', ['gricia'], [['pasta', 90], ['guanciale', 40], ['pecorino', 20]]),
  _P('p-cacio-pepe', 'Cacio e pepe', ['pasta cacio e pepe', 'spaghetti cacio e pepe', 'tonnarelli cacio e pepe'], [['pasta', 90], ['pecorino', 35]]),
  _P('p-pasta-pesto', 'Pasta al pesto', ['trofie al pesto', 'pasta col pesto', 'pasta pesto'], [['pasta', 90], ['pesto', 40], ['parmigiano', 5]]),
  _P('p-ragu', 'Pasta al ragù', ['pasta alla bolognese', 'ragu', 'bolognese', 'tagliatelle al ragu', 'spaghetti alla bolognese', 'pasta al sugo di carne'], [['pasta', 90], ['macinato-manzo', 70], ['passata', 100], ['carote', 15], ['sedano', 10], ['cipolla', 10], ['olio-evo', 5]]),
  _P('p-norma', 'Pasta alla norma', ['norma', 'pasta con le melanzane'], [['pasta', 90], ['melanzane', 150], ['passata', 100], ['ricotta', 20], ['olio-evo', 15]]),
  _P('p-pasta-zucchine', 'Pasta e zucchine', ['pasta alle zucchine', 'pasta zucchine', 'pasta con le zucchine'], [['pasta', 90], ['zucchine', 200], ['olio-evo', 10], ['parmigiano', 10]]),
  _P('p-pasta-broccoli', 'Pasta e broccoli', ['pasta con i broccoli', 'pasta ai broccoli'], [['pasta', 90], ['broccoli', 200], ['olio-evo', 10], ['parmigiano', 10]]),
  _P('p-pasta-piselli', 'Pasta e piselli', ['pasta con i piselli'], [['pasta', 90], ['piselli', 100], ['pancetta', 20], ['olio-evo', 10]]),
  _P('p-pasta-patate', 'Pasta e patate', ['pasta con le patate'], [['pasta', 80], ['patate', 150], ['olio-evo', 10], ['parmigiano', 10]]),
  _P('p-scoglio', 'Pasta allo scoglio', ['spaghetti allo scoglio', 'pasta ai frutti di mare', 'spaghetti ai frutti di mare'], [['pasta', 90], ['cozze', 80], ['vongole', 60], ['gamberi', 60], ['calamari', 60], ['passata', 80], ['olio-evo', 10]]),
  _P('p-pasta-salmone', 'Pasta al salmone', ['pasta panna e salmone', 'pasta salmone'], [['pasta', 90], ['salmone-affumicato', 50], ['panna', 30]]),
  _P('p-pasta-panna-prosciutto', 'Pasta panna e prosciutto', ['pasta prosciutto e panna'], [['pasta', 90], ['cotto', 50], ['panna', 40]]),
  _P('p-arrabbiata', "Penne all'arrabbiata", ['arrabbiata', 'pasta all arrabbiata'], [['pasta', 90], ['passata', 150], ['olio-evo', 10]]),
  _P('p-puttanesca', 'Pasta alla puttanesca', ['puttanesca', 'spaghetti alla puttanesca'], [['pasta', 90], ['passata', 150], ['olive', 20], ['acciughe-olio', 5], ['olio-evo', 10]]),
  _P('p-pasta-cozze', 'Pasta con le cozze', ['spaghetti con le cozze', 'pasta e cozze'], [['pasta', 90], ['cozze', 150], ['olio-evo', 10]]),
  _P('p-gnocchi-sugo', 'Gnocchi al pomodoro', ['gnocchi al sugo', 'gnocchi alla sorrentina'], [['gnocchi', 250], ['passata', 120], ['parmigiano', 10], ['olio-evo', 5]]),
  _P('p-gnocchi-pesto', 'Gnocchi al pesto', [], [['gnocchi', 250], ['pesto', 30]]),
  _P('p-tortellini-brodo', 'Tortellini in brodo', ['cappelletti in brodo'], [['pasta-fresca', 100], ['brodo', 300], ['parmigiano', 10]]),
  _P('p-tortellini-panna', 'Tortellini panna e prosciutto', ['tortellini alla panna'], [['pasta-fresca', 125], ['panna', 40], ['cotto', 30]]),
  _P('p-ravioli-burro', 'Ravioli burro e salvia', ['ravioli al burro'], [['pasta-fresca', 150], ['burro', 15], ['parmigiano', 10]]),
  _P('p-risotto-milanese', 'Risotto alla milanese', ['risotto allo zafferano', 'risotto giallo'], [['riso', 80], ['burro', 15], ['parmigiano', 15], ['brodo', 250], ['cipolla', 10]]),
  _P('p-riso-bianco', 'Riso in bianco', ['riso olio e parmigiano', 'riso bollito'], [['riso', 80], ['olio-evo', 10], ['parmigiano', 10]]),
  _P('p-insalata-riso', 'Insalata di riso', ['riso freddo'], [['riso', 80], ['tonno-naturale', 40], ['wurstel', 30], ['emmental', 20], ['olive', 10], ['olio-evo', 10]]),

  // — Carne
  _P('p-pollo-cacciatora', 'Pollo alla cacciatora', ['pollo in umido'], [['cosce-pollo', 250], ['passata', 120], ['olive', 15], ['cipolla', 30], ['olio-evo', 10]]),
  _P('p-pollo-patate', 'Pollo e patate al forno', ['pollo e patate', 'pollo con patate'], [['cosce-pollo', 250], ['patate', 200], ['olio-evo', 15]]),
  _P('p-spezzatino', 'Spezzatino con patate', ['spezzatino', 'spezzatino di manzo'], [['manzo-spezzatino', 200], ['patate', 150], ['passata', 50], ['carote', 50], ['cipolla', 30], ['olio-evo', 10]]),
  _P('p-arrosto-vitello', 'Arrosto di vitello', ['arrosto di vitello al forno'], [['vitello', 180], ['olio-evo', 10]]),
  _P('p-saltimbocca', 'Saltimbocca alla romana', ['saltimbocca'], [['vitello', 150], ['crudo', 30], ['burro', 10], ['farina', 5]]),
  _P('p-involtini', 'Involtini di carne', ['involtini', 'involtini prosciutto e formaggio'], [['vitello', 150], ['cotto', 30], ['asiago', 20], ['olio-evo', 10]]),
  _P('p-vitello-tonnato', 'Vitello tonnato', [], [['vitello', 150], ['maionese', 30], ['tonno-olio', 30]]),
  _P('p-fegato-veneziana', 'Fegato alla veneziana', [], [['fegato', 180], ['cipolla', 150], ['olio-evo', 15], ['burro', 5]]),
  _P('p-salsiccia-friarielli', 'Salsiccia e friarielli', ['salsiccia e broccoli', 'salsiccia e cime di rapa', 'salsicce e friarielli'], [['salsiccia', 150], ['broccoli', 200], ['olio-evo', 10]]),
  _P('p-salsiccia-patate', 'Salsiccia e patate', ['salsicce e patate'], [['salsiccia', 150], ['patate', 200], ['olio-evo', 10]]),
  _P('p-hamburger-panino', 'Hamburger nel panino', ['panino con hamburger', 'cheeseburger', 'panino hamburger'], [['pane', 80], ['macinato-manzo', 150], ['provolone', 20], ['pomodori', 30], ['misticanza', 10], ['ketchup', 15]]),
  _P('p-carpaccio', 'Carpaccio di manzo', ['carpaccio', 'carpaccio rucola e grana'], [['manzo', 120], ['parmigiano', 15], ['misticanza', 30], ['olio-evo', 10]]),
  _P('p-coniglio-pancetta', 'Coniglio con pancetta', ['coniglio alla pancetta', 'coniglio e pancetta', 'coniglio in padella con pancetta'], [['coniglio', 220], ['pancetta', 30], ['olio-evo', 10]]),
  _P('p-coniglio-cacciatora', 'Coniglio alla cacciatora', ['coniglio in umido'], [['coniglio', 250], ['passata', 100], ['olive', 15], ['olio-evo', 10]]),

  // — Pesce
  _P('p-fritto-misto', 'Fritto misto di pesce', ['frittura di pesce', 'fritto misto', 'frittura mista'], [['calamari', 150], ['gamberi', 100], ['farina', 20], ['olio-semi', 25]]),
  _P('p-zuppa-pesce', 'Zuppa di pesce', ['cacciucco', 'brodetto di pesce'], [['cozze', 100], ['vongole', 80], ['calamari', 100], ['gamberi', 80], ['merluzzo', 100], ['passata', 150], ['olio-evo', 15], ['pane', 40]]),
  _P('p-sogliola-mugnaia', 'Sogliola alla mugnaia', [], [['sogliola', 200], ['farina', 10], ['burro', 15]]),
  _P('p-insalata-mare', 'Insalata di mare', ['antipasto di mare'], [['polpo', 100], ['calamari', 80], ['gamberi', 80], ['cozze', 60], ['sedano', 20], ['olio-evo', 15]]),

  // — Verdure, contorni, piatti unici
  _P('p-caponata', 'Caponata', ['caponata di melanzane'], [['melanzane', 200], ['sedano', 30], ['cipolla', 30], ['olive', 15], ['passata', 60], ['zucchero', 5], ['aceto-balsamico', 10], ['olio-evo', 20]]),
  _P('p-peperonata', 'Peperonata', [], [['peperoni', 250], ['cipolla', 50], ['passata', 60], ['olio-evo', 15]]),
  _P('p-melanzane-funghetto', 'Melanzane a funghetto', [], [['melanzane', 250], ['passata', 50], ['olio-evo', 20]]),
  _P('p-insalata-mista', 'Insalata mista', ['insalata mista con carote', 'contorno di insalata'], [['misticanza', 100], ['pomodori', 100], ['carote', 50], ['olio-evo', 10]]),
  _P('p-insalatona', 'Insalatona', ['insalatona tonno e mozzarella', 'insalata completa'], [['misticanza', 100], ['pomodori', 100], ['mozzarella', 125], ['tonno-naturale', 56], ['olive', 15], ['olio-evo', 10]]),
  _P('p-pure', 'Purè di patate', ['pure', 'pure di patate', 'purea di patate'], [['patate', 200], ['latte', 50], ['burro', 10], ['parmigiano', 5]]),
  _P('p-spinaci-burro', 'Spinaci al burro', [], [['spinaci', 250], ['burro', 10]]),
  _P('p-fagiolini-patate', 'Fagiolini e patate', ['patate e fagiolini'], [['fagiolini', 150], ['patate', 150], ['olio-evo', 10]]),
  _P('p-zuppa-legumi', 'Zuppa di legumi', ['zuppa di legumi misti', 'zuppa di fagioli'], [['fagioli', 100], ['ceci', 100], ['lenticchie', 100], ['passata', 50], ['olio-evo', 10]]),

  // — Colazione, panini, spuntini
  _P('p-latte-cereali', 'Latte e cereali', ['latte con cereali', 'tazza di latte e cereali'], [['latte', 200], ['cornflakes', 40]]),
  _P('p-caffelatte', 'Caffellatte', ['caffe latte', 'caffelatte', 'latte macchiato'], [['latte', 200], ['caffe', 30], ['zucchero', 5]]),
  _P('p-cappuccino-cornetto', 'Cappuccino e cornetto', ['cappuccino e brioche', 'colazione al bar', 'cappuccio e cornetto'], [['cappuccino', 150], ['cornetto', 60]]),
  _P('p-fette-marmellata', 'Fette biscottate e marmellata', ['fette con marmellata', 'fette biscottate con marmellata'], [['fette-biscottate', 30], ['marmellata', 20]]),
  _P('p-pane-nutella', 'Pane e nutella', ['pane con nutella'], [['pane', 50], ['nutella', 20]]),
  _P('p-yogurt-frutta', 'Yogurt e frutta', ['yogurt con frutta', 'yogurt e banana'], [['yogurt-intero', 125], ['banana', 60]]),
  _P('p-porridge', 'Porridge', ['porridge di avena', 'porridge con banana'], [['avena', 40], ['latte', 200], ['banana', 50], ['miele', 5]]),
  _P('p-toast', 'Toast prosciutto e formaggio', ['toast', 'toast cotto e formaggio'], [['pane', 60], ['cotto', 40], ['emmental', 30]]),
  _P('p-avocado-toast', 'Avocado toast con uovo', ['avocado toast', 'toast avocado', 'toast con avocado'], [['pane-integrale', 60], ['avocado', 70], ['uova', 55]]),
  _P('p-macedonia', 'Macedonia', ['macedonia di frutta'], [['mela', 100], ['banana', 60], ['arancia', 80], ['kiwi', 50]]),
  _P('p-panino-crudo-mozzarella', 'Panino crudo e mozzarella', ['panino con prosciutto e mozzarella', 'panino prosciutto e mozzarella'], [['pane', 100], ['crudo', 50], ['mozzarella', 60]]),
  _P('p-panino-mortadella', 'Panino con la mortadella', ['panino mortadella'], [['pane', 100], ['mortadella', 60]]),
  _P('p-tramezzino', 'Tramezzino tonno e pomodoro', ['tramezzino', 'tramezzino al tonno'], [['pane', 50], ['tonno-naturale', 40], ['maionese', 15], ['pomodori', 20]]),
  _P('p-bruschetta', 'Bruschetta al pomodoro', ['bruschette', 'bruschetta'], [['pane', 60], ['pomodori', 100], ['olio-evo', 10]]),
  _P('p-focaccia-farcita', 'Focaccia farcita', ['focaccia con prosciutto', 'focaccia prosciutto e formaggio'], [['focaccia', 120], ['cotto', 40], ['stracchino', 40]]),
];
